// Static map: LeetCode problem number → topic tags
// Used to power /topics/[tag] pages and tag chips on detail pages

export type Tag = string

/** Short editorial description shown at the top of each /topics/[tag] page */
export const TOPIC_DESCRIPTIONS: Record<string, string> = {
  'array': 'Array problems involve manipulating elements stored in a contiguous block of memory. Key techniques include two-pointer traversal, prefix sums, sliding windows, and in-place partitioning. In C#, arrays are zero-indexed and fixed in size — use List<T> when you need dynamic resizing.',
  'string': 'String problems range from simple character counting to complex pattern matching. Common approaches include two pointers, sliding window, prefix hashing, and the KMP algorithm. In C#, strings are immutable — use StringBuilder for efficient concatenation inside loops.',
  'dynamic-programming': 'Dynamic programming solves problems by breaking them into overlapping sub-problems and storing results to avoid redundant work. The key steps are: define state, write a recurrence relation, set base cases, and choose top-down (memoization) or bottom-up (tabulation). DP often yields O(n²) → O(n) time improvements over brute force.',
  'tree': 'Tree problems typically require recursive DFS or iterative BFS. Common patterns: preorder for serialization, inorder for BST sorted output, postorder for bottom-up aggregation. Always consider edge cases: null nodes, single-node trees, and skewed (list-like) trees.',
  'binary-search': 'Binary search reduces search space by half each step, giving O(log n) time. Beyond sorted arrays, apply it on the answer space ("binary search on result") when you can define a monotonic predicate — e.g., "can we achieve X with k resources?"',
  'hash-table': 'Hash tables provide O(1) average-case lookup, insert, and delete. They are the go-to tool for counting frequencies, detecting complements (Two Sum pattern), and caching seen values. In C#, use Dictionary<K,V> for maps and HashSet<T> for membership checks.',
  'math': 'Math problems test number theory, combinatorics, and modular arithmetic. Common tools: GCD/LCM (Euclidean algorithm), prime sieve, modular inverse (Fermat\'s little theorem), digit manipulation, and bit tricks. Overflow is a key concern in C# — use long when products may exceed 2³¹.',
  'two-pointers': 'The two-pointer technique places pointers at different positions (often the two ends) and moves them toward each other. It turns O(n²) nested loops into O(n) sweeps for problems like pair sums, removing duplicates, and container capacity. Works best on sorted or partitioned arrays.',
  'depth-first-search': 'DFS explores as far as possible before backtracking. Use it for path finding, cycle detection, connected components, and tree traversal. Implement recursively (implicit call stack) or iteratively with an explicit Stack<T>. Mark visited nodes to avoid infinite loops in graphs.',
  'breadth-first-search': 'BFS explores nodes level by level, guaranteeing the shortest path in unweighted graphs. Use a Queue<T> and a visited set. Classic applications: shortest path, level-order tree traversal, multi-source distance (e.g., "01 matrix"), and word ladder transformations.',
  'sorting': 'Sorting is often a preprocessing step that enables binary search, two-pointer sweeps, or greedy algorithms. C#\'s Array.Sort() uses an introspective sort (O(n log n)). Custom comparisons use the Comparison<T> delegate or IComparer<T>. Consider counting sort or bucket sort for bounded integer inputs.',
  'greedy': 'Greedy algorithms make locally optimal choices at each step, hoping to reach a global optimum. Greedy works when a problem has the "greedy choice property" and "optimal substructure". Common applications: interval scheduling, activity selection, Huffman coding, and jump game.',
  'stack': 'Stacks support LIFO (last-in, first-out) operations in O(1). Key patterns: balanced parentheses, next greater element (monotonic stack), function call simulation, and undo/redo. A monotonic stack maintains a strictly increasing or decreasing order to answer range queries efficiently.',
  'linked-list': 'Linked list problems often use the fast/slow pointer (Floyd\'s algorithm) for cycle detection and finding the middle, and dummy head nodes for clean insertion/deletion. Reverse operations should be done iteratively to avoid stack overflow on large lists.',
  'backtracking': 'Backtracking explores all possible solutions by building candidates incrementally and abandoning ("pruning") branches that cannot lead to a valid result. It powers N-Queens, Sudoku solver, permutations, and subset generation. Prune early to reduce the effective search space.',
  'sliding-window': 'The sliding window technique maintains a dynamic sub-array (or substring) of interest, expanding the right boundary and shrinking the left boundary based on a constraint. It reduces O(n²) substring enumeration to O(n). Track state (frequency map, sum, distinct count) incrementally.',
  'matrix': 'Matrix problems often involve BFS/DFS flood fill, dynamic programming on 2D grids, or spiral/diagonal traversal. For row × column DP, break it into 1D sub-problems column by column. Common pitfalls: boundary checks and modifying the input matrix in-place.',
  'prefix-sum': 'A prefix sum array pre-computes cumulative values so any range query is answered in O(1). The classic sum of range [l, r] = prefix[r+1] - prefix[l]. 2D prefix sums extend this to matrix sub-rectangle queries. Combine with a hash map for "subarray sum equals k" problems.',
  'bit-manipulation': 'Bit manipulation uses bitwise operators (&, |, ^, ~, <<, >>) for compact and fast solutions. Key tricks: x & (x-1) clears lowest set bit, x ^ x = 0 (XOR cancellation), and bitmask DP represents subsets as integers. In C#, use int (32-bit) or long (64-bit) for bitmasking.',
  'heap': 'A heap (priority queue) gives O(log n) insert and O(1) peek with O(log n) removal. In C#, use PriorityQueue<TElement, TPriority> (.NET 6+). Classic patterns: top-K elements (min-heap of size K), merge K sorted lists, Dijkstra\'s shortest path, and median in a stream (two heaps).',
  'monotonic-stack': 'A monotonic stack maintains elements in strictly increasing or decreasing order. When a new element violates this order, elements are popped and processed. Use for "next greater / smaller element", histogram area, and stock span problems. Each element is pushed and popped at most once — O(n) overall.',
  'graph': 'Graph algorithms model relationships between entities. Core algorithms: DFS/BFS for traversal, Dijkstra for weighted shortest path, Bellman-Ford for negative weights, Floyd-Warshall for all-pairs, and Kruskal/Prim for minimum spanning trees. Represent graphs as adjacency lists (Dictionary<int, List<int>>) for efficiency.',
  'union-find': 'Union-Find (Disjoint Set Union) tracks connected components efficiently. Operations: Find (with path compression) and Union (by rank). Achieves near-O(1) per operation (O(α(n)) amortized). Classic uses: Kruskal\'s MST, detecting undirected graph cycles, and grouping equivalent elements.',
  'trie': 'A trie (prefix tree) stores strings character by character, enabling O(L) insert, search, and prefix queries where L is string length. Use it for autocomplete, word search in a grid, longest common prefix, and IP routing. Each node has up to 26 children (for lowercase letters).',
  'design': 'Design problems ask you to implement a data structure or system with specific API contracts. Common designs: LRU Cache (HashMap + doubly linked list), LFU Cache, Min Stack, Iterator, and streaming median. Focus on the time complexity required for each operation.',
  'recursion': 'Recursion solves a problem by calling itself with a smaller sub-problem. Every recursive solution needs: a base case (to stop) and a recursive case (to reduce). Stack space is O(depth). Convert deep recursion to iteration with an explicit stack when stack overflow is a concern.',
  'queue': 'Queues support FIFO (first-in, first-out) operations. In C#, Queue<T> provides O(1) enqueue/dequeue. Key patterns: BFS, sliding window maximum (deque), and task scheduling. A double-ended queue (LinkedList<T> or ArrayDeque) supports both front and back operations.',
  'binary-tree': 'Binary trees have at most two children per node. Master the three DFS orders (pre/in/post) and level-order BFS. Key problems: height, diameter, path sum, lowest common ancestor, and serialization. Recursive solutions are clean but watch recursion depth for very deep trees.',
  'binary-search-tree': 'A BST maintains the invariant: left subtree values < node < right subtree values. This gives O(h) search/insert/delete; O(log n) for balanced trees. In-order traversal yields sorted output. Use range checks ([min, max]) to validate BST property and find floor/ceiling.',
  'divide-and-conquer': 'Divide and conquer splits a problem into independent sub-problems, solves each recursively, and combines the results. Classic examples: merge sort, quick sort, binary search, and closest pair of points. Master Theorem helps analyze time complexity: T(n) = aT(n/b) + f(n).',
  'simulation': 'Simulation problems require implementing the described process step by step. Focus on correctly handling edge cases and state transitions. Common in geometry, game problems, and string manipulation. Optimize only if the naive simulation exceeds the time limit.',
  'counting': 'Counting problems enumerate valid configurations without explicitly generating them. Techniques: combinatorics (nCr), inclusion-exclusion, digit DP, and contribution of each element. In C#, use long to avoid overflow when multiplying counts.',
  'memoization': 'Memoization caches the return value of a function for each unique input, converting exponential recursion to polynomial time. Use a Dictionary<(int, int), int> or a 2D array. Identify the "state" (all parameters that uniquely determine the result) to design the cache key.',
  'topological-sort': 'Topological sort produces a linear ordering of a DAG where each node comes before its descendants. Two algorithms: DFS (post-order reversal) and BFS Kahn\'s (process nodes with in-degree 0). Applications: course scheduling, build dependency resolution, and task ordering.',
  'segment-tree': 'Segment trees support range queries (sum, min, max, GCD) and point updates in O(log n). Build in O(n) by filling leaves, then propagating upward. Lazy propagation enables range updates in O(log n) as well. Use for competitive programming range-query problems.',
  'binary-indexed-tree': 'A Fenwick tree (BIT) answers prefix-sum queries and point updates in O(log n) with O(n) space — simpler to implement than a segment tree. Index arithmetic uses i += i & (-i) to traverse. Use for inversion counting, order statistics, and frequency prefix sums.',
  'geometry': 'Geometry problems involve coordinates, lines, circles, and polygons. Key tools: cross product (orientation, area), dot product (angle), Graham scan (convex hull), and line intersection. Use long arithmetic to avoid floating-point errors when possible.',
  'game-theory': 'Combinatorial game theory analyzes who wins under optimal play. Sprague-Grundy theorem assigns "nim-values" to game states. For simple games, look for patterns in small cases. Minimax (with alpha-beta pruning) solves general two-player zero-sum games.',
  'number-theory': 'Number theory problems involve primes, divisors, GCD, modular arithmetic, and number bases. Key algorithms: Sieve of Eratosthenes (O(n log log n) primes), Euclidean GCD (O(log n)), and modular exponentiation (O(log n)). Most competitive problems use modulo 10⁹+7.',
  'string-matching': 'String matching finds occurrences of a pattern in text. KMP runs in O(n+m) using a failure function to skip redundant comparisons. Rabin-Karp uses rolling hashes for average O(n+m). Z-algorithm and suffix arrays support more general substring queries.',
  'ordered-set': 'An ordered set (e.g., SortedSet<T> in C#) maintains elements in sorted order with O(log n) insert/delete/lookup. Use it when you need both fast membership testing and order-based queries (floor, ceiling, predecessor, successor).',
  'rolling-hash': 'Rolling hash computes a new hash from the previous one in O(1) by removing the outgoing character and adding the incoming one. Used in Rabin-Karp string matching and detecting duplicate substrings. Choose a large prime modulus and base to minimize collisions.',
  'shortest-path': 'Shortest path algorithms find minimum-cost routes in graphs. Dijkstra (non-negative weights, O((V+E) log V)), Bellman-Ford (negative edges, O(VE)), Floyd-Warshall (all-pairs, O(V³)), and BFS (unweighted, O(V+E)). In C#, use PriorityQueue for Dijkstra.',
  'monotonic-queue': 'A monotonic queue (deque) answers sliding window min/max in O(1) amortized. Maintain indices in decreasing (for max) or increasing (for min) order. Remove from the front when indices fall outside the window, and from the back when the new element is more extreme.',
  'bitmask': 'Bitmask DP represents a subset of n items as a single integer (bit i = 1 means item i is included). Enables O(2ⁿ · n) DP over all subsets — practical up to n ≈ 20. Classic: Travelling Salesman, covering problems, and assignment problems.',
  'difference-array': 'A difference array enables range increment updates in O(1): diff[l] += v, diff[r+1] -= v. Reconstruct the original array with a prefix sum. Use for event sweep problems, overlapping intervals, and paint-range queries. 2D extension handles matrix range updates.',
  'merge-sort': 'Merge sort divides an array into two halves, sorts each, and merges. It runs in O(n log n) worst case with O(n) extra space. The merge step can count inversions or merge sorted linked lists. Stable sort — relative order of equal elements is preserved.',
  'binary-lifting': 'Binary lifting precomputes 2ᵏ-th ancestors for each node in O(n log n). LCA (lowest common ancestor) queries then run in O(log n). Useful in competitive programming for tree path queries and jumping k-steps efficiently.',
  'eulerian-circuit': 'An Eulerian circuit visits every edge exactly once. It exists in a directed graph iff every node has equal in-degree and out-degree, and the graph is connected. Hierholzer\'s algorithm finds it in O(E). Applications: DNA assembly and route planning.',
  'hash-function': 'Custom hash functions reduce collisions in hash maps. Polynomial rolling hash H(s) = s[0]·pⁿ⁻¹ + ... + s[n-1] is common for strings. Use double hashing (two independent hashes) to reduce collision probability to near zero.',
  'doubly-linked-list': 'A doubly linked list has both prev and next pointers, enabling O(1) insertion/deletion at any known node. It underlies LRU Cache, browser history, and undo stacks. In C#, LinkedList<T> is a doubly linked list with O(1) AddFirst/AddLast/Remove(node).',
  'probability-and-statistics': 'Probability problems may require expected value computation, random sampling, or reservoir sampling. Key concepts: linearity of expectation, conditional probability, and geometric distribution. Reservoir sampling picks k items from a stream of unknown length in O(n) time and O(k) space.',
  'brain-teaser': 'Brain teaser problems require creative insight rather than standard algorithms. Read the problem carefully for hidden constraints or mathematical shortcuts. Common tricks: parity arguments, invariants, and symmetry breaking. These problems often have elegant O(1) or O(n) solutions once the key observation is found.',
}

export const TAG_LABELS: Record<string, string> = {
  'array': 'Array',
  'string': 'String',
  'dynamic-programming': 'Dynamic Programming',
  'tree': 'Tree',
  'binary-search': 'Binary Search',
  'hash-table': 'Hash Table',
  'math': 'Math',
  'two-pointers': 'Two Pointers',
  'depth-first-search': 'Depth-First Search',
  'breadth-first-search': 'Breadth-First Search',
  'sorting': 'Sorting',
  'greedy': 'Greedy',
  'stack': 'Stack',
  'linked-list': 'Linked List',
  'backtracking': 'Backtracking',
  'sliding-window': 'Sliding Window',
  'matrix': 'Matrix',
  'prefix-sum': 'Prefix Sum',
  'bit-manipulation': 'Bit Manipulation',
  'heap': 'Heap (Priority Queue)',
  'monotonic-stack': 'Monotonic Stack',
  'graph': 'Graph',
  'union-find': 'Union Find',
  'trie': 'Trie',
  'design': 'Design',
  'recursion': 'Recursion',
  'queue': 'Queue',
  'binary-tree': 'Binary Tree',
  'binary-search-tree': 'Binary Search Tree',
  'divide-and-conquer': 'Divide and Conquer',
  'simulation': 'Simulation',
  'counting': 'Counting',
  'memoization': 'Memoization',
  'topological-sort': 'Topological Sort',
  'segment-tree': 'Segment Tree',
  'binary-indexed-tree': 'Binary Indexed Tree',
  'geometry': 'Geometry',
  'game-theory': 'Game Theory',
  'number-theory': 'Number Theory',
  'string-matching': 'String Matching',
  'ordered-set': 'Ordered Set',
  'rolling-hash': 'Rolling Hash',
  'javascript': 'JavaScript',
  'database': 'Database',
  'shell': 'Shell',
  'probability-and-statistics': 'Probability & Statistics',
  'shortest-path': 'Shortest Path',
  'brain-teaser': 'Brain Teaser',
  'monotonic-queue': 'Monotonic Queue',
  'bitmask': 'Bitmask',
  'difference-array': 'Difference Array',
  'merge-sort': 'Merge Sort',
  'binary-lifting': 'Binary Lifting',
  'eulerian-circuit': 'Eulerian Circuit',
  'hash-function': 'Hash Function',
  'doubly-linked-list': 'Doubly Linked List',
}

// Problem number → tags
export const PROBLEM_TAGS: Record<number, Tag[]> = {
  1:   ['array', 'hash-table'],
  2:   ['linked-list', 'math', 'recursion'],
  3:   ['string', 'sliding-window', 'hash-table'],
  4:   ['array', 'binary-search', 'divide-and-conquer'],
  5:   ['string', 'dynamic-programming'],
  6:   ['string', 'simulation'],
  7:   ['math'],
  8:   ['string', 'math'],
  9:   ['math'],
  10:  ['string', 'dynamic-programming', 'recursion'],
  11:  ['array', 'two-pointers', 'greedy'],
  12:  ['math', 'string'],
  13:  ['math', 'string'],
  14:  ['string'],
  15:  ['array', 'two-pointers', 'sorting'],
  16:  ['array', 'two-pointers', 'sorting'],
  17:  ['string', 'backtracking'],
  18:  ['array', 'two-pointers', 'sorting'],
  19:  ['linked-list', 'two-pointers'],
  20:  ['string', 'stack'],
  21:  ['linked-list', 'recursion'],
  22:  ['string', 'backtracking', 'dynamic-programming'],
  23:  ['linked-list', 'heap', 'divide-and-conquer'],
  24:  ['linked-list', 'recursion'],
  25:  ['linked-list', 'recursion'],
  26:  ['array', 'two-pointers'],
  27:  ['array', 'two-pointers'],
  28:  ['string', 'two-pointers', 'string-matching'],
  29:  ['math', 'bit-manipulation'],
  30:  ['string', 'hash-table', 'sliding-window'],
  31:  ['array'],
  32:  ['string', 'stack', 'dynamic-programming'],
  33:  ['array', 'binary-search'],
  34:  ['array', 'binary-search'],
  35:  ['array', 'binary-search'],
  36:  ['array', 'hash-table', 'matrix'],
  37:  ['array', 'backtracking', 'matrix'],
  38:  ['string'],
  39:  ['array', 'backtracking'],
  40:  ['array', 'backtracking'],
  41:  ['array', 'hash-table'],
  42:  ['array', 'two-pointers', 'dynamic-programming', 'stack', 'monotonic-stack'],
  43:  ['math', 'string'],
  44:  ['string', 'dynamic-programming', 'greedy'],
  45:  ['array', 'dynamic-programming', 'greedy', 'breadth-first-search'],
  46:  ['array', 'backtracking'],
  47:  ['array', 'backtracking'],
  48:  ['array', 'math', 'matrix'],
  49:  ['array', 'hash-table', 'string', 'sorting'],
  50:  ['math', 'recursion'],
  51:  ['array', 'backtracking'],
  52:  ['array', 'backtracking'],
  53:  ['array', 'dynamic-programming', 'divide-and-conquer'],
  54:  ['array', 'matrix', 'simulation'],
  55:  ['array', 'dynamic-programming', 'greedy'],
  56:  ['array', 'sorting'],
  57:  ['array'],
  58:  ['array', 'string'],
  59:  ['array', 'matrix', 'simulation'],
  60:  ['math', 'recursion'],
  61:  ['linked-list', 'two-pointers'],
  62:  ['math', 'dynamic-programming'],
  63:  ['array', 'dynamic-programming'],
  64:  ['array', 'dynamic-programming', 'matrix'],
  66:  ['array', 'math'],
  67:  ['math', 'string', 'bit-manipulation'],
  69:  ['math', 'binary-search'],
  70:  ['math', 'dynamic-programming', 'memoization'],
  71:  ['string', 'stack'],
  72:  ['string', 'dynamic-programming'],
  73:  ['array', 'hash-table', 'matrix'],
  74:  ['array', 'binary-search', 'matrix'],
  75:  ['array', 'two-pointers', 'sorting'],
  76:  ['string', 'hash-table', 'sliding-window'],
  77:  ['array', 'backtracking'],
  78:  ['array', 'backtracking', 'bit-manipulation'],
  79:  ['array', 'backtracking', 'matrix', 'depth-first-search'],
  80:  ['array', 'two-pointers'],
  82:  ['linked-list', 'two-pointers'],
  83:  ['linked-list'],
  84:  ['array', 'stack', 'monotonic-stack'],
  85:  ['array', 'stack', 'dynamic-programming', 'matrix'],
  86:  ['linked-list', 'two-pointers'],
  88:  ['array', 'two-pointers', 'sorting'],
  90:  ['array', 'backtracking', 'bit-manipulation'],
  91:  ['string', 'dynamic-programming'],
  92:  ['linked-list'],
  94:  ['tree', 'depth-first-search', 'binary-tree', 'stack'],
  95:  ['dynamic-programming', 'binary-tree'],
  96:  ['math', 'dynamic-programming', 'binary-search-tree'],
  97:  ['string', 'dynamic-programming'],
  98:  ['tree', 'depth-first-search', 'binary-search-tree'],
  99:  ['tree', 'depth-first-search', 'binary-search-tree'],
  100: ['tree', 'depth-first-search', 'binary-tree'],
  101: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  102: ['tree', 'breadth-first-search', 'binary-tree'],
  103: ['tree', 'breadth-first-search', 'binary-tree', 'stack'],
  104: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  105: ['array', 'hash-table', 'tree', 'binary-tree', 'divide-and-conquer'],
  106: ['array', 'hash-table', 'tree', 'binary-tree', 'divide-and-conquer'],
  107: ['tree', 'breadth-first-search', 'binary-tree'],
  108: ['array', 'tree', 'binary-search-tree', 'binary-tree', 'divide-and-conquer'],
  110: ['tree', 'depth-first-search', 'binary-tree'],
  111: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  112: ['tree', 'depth-first-search', 'binary-tree'],
  113: ['tree', 'depth-first-search', 'backtracking', 'binary-tree'],
  114: ['linked-list', 'stack', 'tree', 'depth-first-search', 'binary-tree'],
  116: ['linked-list', 'tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  118: ['array', 'dynamic-programming'],
  119: ['array', 'dynamic-programming'],
  120: ['array', 'dynamic-programming'],
  121: ['array', 'dynamic-programming'],
  122: ['array', 'dynamic-programming', 'greedy'],
  123: ['array', 'dynamic-programming'],
  124: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  125: ['two-pointers', 'string'],
  126: ['hash-table', 'string', 'backtracking', 'breadth-first-search', 'graph'],
  127: ['hash-table', 'string', 'breadth-first-search', 'graph'],
  128: ['array', 'hash-table', 'union-find'],
  129: ['tree', 'depth-first-search', 'binary-tree'],
  130: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  131: ['string', 'dynamic-programming', 'backtracking'],
  132: ['string', 'dynamic-programming'],
  133: ['hash-table', 'depth-first-search', 'breadth-first-search', 'graph'],
  134: ['array', 'greedy'],
  135: ['array', 'greedy'],
  136: ['array', 'bit-manipulation'],
  137: ['array', 'bit-manipulation'],
  139: ['array', 'hash-table', 'string', 'dynamic-programming', 'trie'],
  140: ['hash-table', 'string', 'dynamic-programming', 'backtracking', 'trie'],
  141: ['hash-table', 'linked-list', 'two-pointers'],
  142: ['hash-table', 'linked-list', 'two-pointers'],
  143: ['linked-list', 'two-pointers', 'stack', 'recursion'],
  144: ['stack', 'tree', 'depth-first-search', 'binary-tree'],
  145: ['stack', 'tree', 'depth-first-search', 'binary-tree'],
  146: ['hash-table', 'linked-list', 'design'],
  148: ['linked-list', 'two-pointers', 'divide-and-conquer', 'sorting'],
  150: ['array', 'math', 'stack'],
  151: ['two-pointers', 'string'],
  152: ['array', 'dynamic-programming'],
  153: ['array', 'binary-search'],
  154: ['array', 'binary-search'],
  155: ['stack', 'design'],
  160: ['linked-list', 'hash-table', 'two-pointers'],
  162: ['array', 'binary-search'],
  167: ['array', 'two-pointers', 'binary-search'],
  168: ['math', 'string'],
  169: ['array', 'hash-table', 'divide-and-conquer', 'sorting', 'counting'],
  189: ['array', 'math', 'two-pointers'],
  190: ['bit-manipulation', 'divide-and-conquer'],
  191: ['bit-manipulation'],
  198: ['array', 'dynamic-programming'],
  199: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  200: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  201: ['bit-manipulation'],
  202: ['hash-table', 'math', 'two-pointers'],
  203: ['linked-list', 'recursion'],
  205: ['hash-table', 'string'],
  206: ['linked-list', 'recursion'],
  207: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  208: ['hash-table', 'string', 'design', 'trie'],
  209: ['array', 'binary-search', 'sliding-window', 'prefix-sum'],
  210: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  211: ['string', 'depth-first-search', 'design', 'trie'],
  212: ['array', 'string', 'backtracking', 'matrix', 'trie'],
  213: ['array', 'dynamic-programming'],
  215: ['array', 'divide-and-conquer', 'sorting', 'heap'],
  216: ['array', 'backtracking'],
  217: ['array', 'hash-table', 'sorting'],
  218: ['array', 'divide-and-conquer', 'binary-search', 'sorting', 'heap', 'ordered-set'],
  219: ['array', 'hash-table', 'sliding-window'],
  220: ['array', 'sorting', 'sliding-window', 'ordered-set'],
  221: ['array', 'dynamic-programming', 'matrix'],
  222: ['tree', 'depth-first-search', 'binary-search', 'binary-tree'],
  224: ['string', 'stack', 'recursion'],
  226: ['tree', 'depth-first-search', 'binary-tree'],
  227: ['math', 'string', 'stack'],
  229: ['array', 'hash-table', 'sorting', 'counting'],
  230: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  231: ['math', 'bit-manipulation'],
  232: ['stack', 'design', 'queue'],
  234: ['linked-list', 'two-pointers', 'stack', 'recursion'],
  235: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  236: ['tree', 'depth-first-search', 'binary-tree'],
  237: ['linked-list'],
  238: ['array', 'prefix-sum'],
  239: ['array', 'queue', 'sliding-window', 'heap', 'monotonic-stack'],
  240: ['array', 'binary-search', 'divide-and-conquer', 'matrix'],
  242: ['hash-table', 'string', 'sorting'],
  257: ['tree', 'depth-first-search', 'string', 'backtracking', 'binary-tree'],
  260: ['array', 'bit-manipulation'],
  263: ['math'],
  264: ['hash-table', 'math', 'dynamic-programming', 'heap'],
  268: ['array', 'hash-table', 'math', 'bit-manipulation', 'sorting'],
  269: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  273: ['math', 'string', 'recursion'],
  278: ['array', 'binary-search'],
  279: ['math', 'dynamic-programming', 'breadth-first-search'],
  283: ['array', 'two-pointers'],
  287: ['array', 'two-pointers', 'binary-search', 'bit-manipulation', 'hash-table'],
  289: ['array', 'matrix', 'simulation'],
  295: ['two-pointers', 'design', 'sorting', 'heap'],
  297: ['string', 'tree', 'depth-first-search', 'breadth-first-search', 'design', 'binary-tree'],
  300: ['array', 'binary-search', 'dynamic-programming'],
  303: ['array', 'design', 'prefix-sum'],
  304: ['array', 'design', 'prefix-sum', 'matrix'],
  307: ['array', 'design', 'binary-indexed-tree', 'segment-tree'],
  309: ['array', 'dynamic-programming'],
  312: ['array', 'dynamic-programming'],
  315: ['array', 'binary-search', 'divide-and-conquer', 'binary-indexed-tree', 'segment-tree'],
  316: ['string', 'stack', 'greedy', 'monotonic-stack'],
  322: ['array', 'dynamic-programming', 'breadth-first-search'],
  323: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  326: ['math', 'recursion'],
  328: ['linked-list', 'two-pointers'],
  329: ['array', 'depth-first-search', 'breadth-first-search', 'dynamic-programming', 'topological-sort', 'memoization', 'matrix'],
  337: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  338: ['dynamic-programming', 'bit-manipulation'],
  341: ['stack', 'tree', 'depth-first-search', 'design'],
  343: ['math', 'dynamic-programming'],
  344: ['two-pointers', 'string', 'recursion'],
  345: ['two-pointers', 'string'],
  347: ['array', 'hash-table', 'divide-and-conquer', 'sorting', 'heap', 'counting'],
  349: ['array', 'hash-table', 'two-pointers', 'binary-search', 'sorting'],
  350: ['array', 'hash-table', 'two-pointers', 'binary-search', 'sorting'],
  354: ['array', 'binary-search', 'dynamic-programming', 'sorting'],
  371: ['math', 'bit-manipulation'],
  373: ['array', 'binary-search', 'sorting', 'heap', 'matrix'],
  374: ['math', 'binary-search'],
  376: ['array', 'greedy', 'dynamic-programming'],
  377: ['array', 'dynamic-programming', 'backtracking'],
  378: ['array', 'binary-search', 'sorting', 'heap', 'matrix'],
  380: ['hash-table', 'array', 'math', 'design'],
  382: ['linked-list', 'math'],
  383: ['hash-table', 'string', 'counting'],
  384: ['array', 'math', 'design', 'sorting'],
  389: ['hash-table', 'string', 'sorting', 'bit-manipulation'],
  392: ['two-pointers', 'string', 'dynamic-programming'],
  394: ['string', 'stack', 'recursion'],
  395: ['hash-table', 'string', 'sliding-window'],
  397: ['math', 'dynamic-programming', 'bit-manipulation', 'greedy'],
  399: ['array', 'math', 'depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  402: ['string', 'stack', 'greedy', 'monotonic-stack'],
  403: ['array', 'dynamic-programming', 'breadth-first-search'],
  406: ['array', 'greedy', 'sorting'],
  409: ['hash-table', 'string', 'greedy'],
  410: ['array', 'binary-search', 'dynamic-programming', 'greedy', 'prefix-sum'],
  412: ['math', 'string', 'simulation'],
  416: ['array', 'dynamic-programming'],
  417: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  421: ['array', 'hash-table', 'bit-manipulation', 'trie'],
  424: ['hash-table', 'string', 'sliding-window'],
  435: ['array', 'dynamic-programming', 'greedy', 'sorting'],
  437: ['tree', 'depth-first-search', 'binary-tree', 'prefix-sum'],
  438: ['hash-table', 'string', 'sliding-window'],
  442: ['array', 'hash-table', 'sorting'],
  445: ['linked-list', 'math', 'stack'],
  448: ['array', 'hash-table'],
  450: ['tree', 'binary-search-tree', 'binary-tree'],
  451: ['hash-table', 'string', 'sorting', 'counting'],
  452: ['array', 'greedy', 'sorting'],
  454: ['array', 'hash-table'],
  456: ['array', 'stack', 'binary-search', 'monotonic-stack'],
  460: ['hash-table', 'linked-list', 'design'],
  461: ['bit-manipulation'],
  462: ['array', 'math', 'sorting', 'two-pointers'],
  472: ['array', 'string', 'dynamic-programming', 'trie'],
  473: ['array', 'dynamic-programming', 'backtracking', 'bit-manipulation'],
  474: ['array', 'string', 'dynamic-programming'],
  476: ['bit-manipulation'],
  480: ['array', 'hash-table', 'sliding-window', 'heap', 'ordered-set'],
  485: ['array'],
  486: ['array', 'math', 'dynamic-programming', 'game-theory'],
  491: ['array', 'hash-table', 'backtracking'],
  494: ['array', 'dynamic-programming', 'backtracking'],
  496: ['array', 'hash-table', 'stack', 'monotonic-stack'],
  498: ['array', 'matrix', 'simulation'],
  503: ['array', 'stack', 'monotonic-stack'],
  509: ['math', 'dynamic-programming', 'recursion', 'memoization'],
  516: ['string', 'dynamic-programming'],
  518: ['array', 'dynamic-programming'],
  523: ['array', 'hash-table', 'math', 'prefix-sum'],
  525: ['array', 'hash-table', 'prefix-sum'],
  530: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  535: ['hash-table', 'math', 'string', 'design'],
  538: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  540: ['array', 'binary-search'],
  542: ['array', 'dynamic-programming', 'breadth-first-search', 'matrix'],
  543: ['tree', 'depth-first-search', 'binary-tree'],
  547: ['depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  556: ['math', 'two-pointers', 'string'],
  557: ['two-pointers', 'string'],
  560: ['array', 'hash-table', 'prefix-sum'],
  561: ['array', 'greedy', 'sorting'],
  566: ['array', 'matrix', 'simulation'],
  567: ['hash-table', 'two-pointers', 'string', 'sliding-window'],
  572: ['tree', 'depth-first-search', 'string-matching', 'binary-tree', 'rolling-hash'],
  581: ['array', 'two-pointers', 'stack', 'greedy', 'sorting', 'monotonic-stack'],
  583: ['string', 'dynamic-programming'],
  594: ['array', 'hash-table', 'sliding-window', 'counting'],
  598: ['math'],
  600: ['dynamic-programming'],
  605: ['array', 'greedy'],
  611: ['array', 'two-pointers', 'binary-search', 'sorting'],
  621: ['array', 'hash-table', 'greedy', 'sorting', 'heap', 'counting'],
  622: ['linked-list', 'design', 'queue'],
  623: ['tree', 'breadth-first-search', 'binary-tree'],
  629: ['dynamic-programming'],
  632: ['array', 'hash-table', 'greedy', 'sliding-window', 'heap'],
  633: ['math', 'binary-search', 'two-pointers'],
  636: ['string', 'stack'],
  637: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  638: ['array', 'dynamic-programming', 'backtracking', 'memoization'],
  641: ['array', 'linked-list', 'design', 'queue'],
  643: ['array', 'sliding-window'],
  645: ['array', 'math'],
  646: ['array', 'dynamic-programming', 'sorting'],
  647: ['two-pointers', 'string', 'dynamic-programming'],
  648: ['array', 'hash-table', 'string', 'trie', 'sorting'],
  650: ['math', 'dynamic-programming'],
  652: ['hash-table', 'tree', 'depth-first-search', 'binary-tree'],
  653: ['array', 'hash-table', 'two-pointers', 'tree', 'binary-search-tree', 'sorting', 'binary-tree'],
  654: ['array', 'divide-and-conquer', 'stack', 'tree', 'monotonic-stack', 'binary-tree'],
  662: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  664: ['string', 'dynamic-programming'],
  665: ['array', 'greedy'],
  669: ['tree', 'binary-search-tree', 'binary-tree'],
  670: ['greedy', 'math'],
  673: ['array', 'math', 'binary-search', 'dynamic-programming'],
  674: ['array'],
  676: ['hash-table', 'string', 'design', 'trie'],
  677: ['hash-table', 'design', 'trie', 'prefix-sum'],
  684: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  685: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  686: ['string'],
  687: ['tree', 'depth-first-search', 'binary-tree'],
  688: ['dynamic-programming'],
  690: ['hash-table', 'tree', 'depth-first-search', 'breadth-first-search'],
  692: ['array', 'hash-table', 'string', 'sorting', 'heap', 'counting', 'trie'],
  695: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  696: ['two-pointers', 'string', 'dynamic-programming'],
  697: ['array', 'hash-table', 'counting'],
  698: ['array', 'dynamic-programming', 'backtracking', 'bit-manipulation'],
  700: ['tree', 'binary-search-tree', 'binary-tree'],
  701: ['tree', 'binary-search-tree', 'binary-tree'],
  703: ['tree', 'design', 'binary-search-tree', 'binary-tree', 'heap'],
  704: ['array', 'binary-search'],
  712: ['string', 'dynamic-programming'],
  713: ['array', 'binary-search', 'prefix-sum', 'sliding-window', 'two-pointers'],
  714: ['array', 'dynamic-programming', 'greedy'],
  718: ['array', 'binary-search', 'dynamic-programming', 'sliding-window', 'rolling-hash'],
  720: ['array', 'hash-table', 'string', 'trie'],
  721: ['array', 'hash-table', 'union-find', 'string'],
  724: ['array', 'prefix-sum'],
  726: ['hash-table', 'string', 'stack', 'math', 'recursion', 'counting'],
  729: ['array', 'binary-search', 'design', 'ordered-set', 'segment-tree'],
  733: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  735: ['array', 'stack', 'simulation'],
  739: ['array', 'stack', 'monotonic-stack'],
  740: ['array', 'hash-table', 'dynamic-programming'],
  743: ['depth-first-search', 'breadth-first-search', 'graph', 'heap'],
  746: ['array', 'dynamic-programming'],
  752: ['array', 'hash-table', 'breadth-first-search'],
  759: ['array', 'greedy', 'heap', 'sorting', 'ordered-set'],
  763: ['array', 'hash-table', 'two-pointers', 'string', 'greedy'],
  765: ['array', 'hash-table', 'greedy', 'two-pointers', 'union-find', 'sorting'],
  766: ['array', 'matrix'],
  767: ['string', 'hash-table', 'greedy', 'sorting', 'heap', 'counting'],
  769: ['array', 'stack', 'greedy', 'sorting', 'monotonic-stack'],
  771: ['hash-table', 'string', 'counting'],
  773: ['array', 'hash-table', 'breadth-first-search', 'matrix'],
  778: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix', 'heap'],
  783: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  784: ['string', 'backtracking', 'bit-manipulation'],
  785: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  787: ['dynamic-programming', 'depth-first-search', 'breadth-first-search', 'graph', 'heap'],
  790: ['dynamic-programming', 'matrix'],
  791: ['array', 'hash-table', 'string', 'sorting'],
  792: ['array', 'string', 'trie', 'rolling-hash', 'string-matching'],
  797: ['depth-first-search', 'breadth-first-search', 'graph', 'backtracking'],
  801: ['array', 'dynamic-programming', 'greedy'],
  802: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort', 'memoization'],
  820: ['array', 'hash-table', 'string', 'trie'],
  837: ['math', 'dynamic-programming'],
  841: ['hash-table', 'depth-first-search', 'breadth-first-search', 'graph'],
  844: ['two-pointers', 'string', 'stack', 'simulation'],
  845: ['array', 'two-pointers'],
  846: ['array', 'hash-table', 'greedy'],
  849: ['array', 'two-pointers', 'greedy'],
  852: ['array', 'binary-search'],
  860: ['array', 'greedy'],
  861: ['array', 'greedy', 'matrix', 'bit-manipulation'],
  862: ['array', 'hash-table', 'queue', 'sliding-window', 'monotonic-stack', 'prefix-sum'],
  864: ['array', 'hash-table', 'breadth-first-search', 'bit-manipulation', 'matrix'],
  867: ['array', 'matrix', 'simulation'],
  869: ['hash-table', 'math', 'sorting', 'counting'],
  871: ['array', 'dynamic-programming', 'greedy', 'heap'],
  872: ['tree', 'depth-first-search', 'binary-tree'],
  875: ['array', 'binary-search'],
  876: ['linked-list', 'two-pointers'],
  877: ['array', 'math', 'dynamic-programming', 'game-theory'],
  881: ['array', 'greedy', 'sorting', 'two-pointers'],
  884: ['array', 'hash-table', 'string', 'counting'],
  890: ['array', 'hash-table', 'string'],
  892: ['array', 'math', 'geometry'],
  894: ['dynamic-programming', 'binary-tree'],
  896: ['array'],
  897: ['stack', 'tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  901: ['stack', 'design', 'monotonic-stack'],
  904: ['array', 'hash-table', 'sliding-window'],
  907: ['array', 'stack', 'monotonic-stack'],
  909: ['array', 'hash-table', 'breadth-first-search', 'matrix'],
  912: ['array', 'sorting', 'divide-and-conquer', 'heap'],
  917: ['two-pointers', 'string'],
  918: ['array', 'dynamic-programming', 'queue', 'monotonic-stack'],
  919: ['tree', 'breadth-first-search', 'design', 'binary-tree'],
  921: ['string', 'stack', 'greedy'],
  923: ['array', 'hash-table', 'two-pointers', 'sorting', 'counting'],
  925: ['array', 'string', 'two-pointers'],
  926: ['string', 'dynamic-programming'],
  929: ['array', 'hash-table', 'string'],
  930: ['array', 'hash-table', 'prefix-sum', 'sliding-window'],
  931: ['array', 'dynamic-programming', 'matrix'],
  934: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  937: ['array', 'string', 'sorting'],
  938: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  941: ['array', 'two-pointers'],
  942: ['string', 'greedy'],
  945: ['array', 'greedy', 'sorting'],
  946: ['array', 'stack', 'simulation'],
  947: ['array', 'depth-first-search', 'union-find', 'graph'],
  948: ['array', 'greedy', 'sorting'],
  950: ['array', 'queue', 'simulation', 'sorting'],
  951: ['tree', 'depth-first-search', 'binary-tree'],
  953: ['array', 'hash-table', 'string'],
  954: ['array', 'hash-table', 'greedy', 'sorting'],
  958: ['tree', 'breadth-first-search', 'binary-tree'],
  959: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  962: ['array', 'stack', 'monotonic-stack'],
  968: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  973: ['array', 'math', 'divide-and-conquer', 'sorting', 'heap', 'quickselect', 'geometry'],
  974: ['array', 'hash-table', 'prefix-sum'],
  976: ['array', 'math', 'greedy', 'sorting', 'geometry'],
  977: ['array', 'two-pointers', 'sorting'],
  979: ['tree', 'depth-first-search', 'binary-tree'],
  980: ['array', 'dynamic-programming', 'backtracking', 'matrix'],
  983: ['array', 'dynamic-programming'],
  986: ['array', 'two-pointers'],
  987: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  988: ['tree', 'depth-first-search', 'binary-tree'],
  990: ['array', 'hash-table', 'union-find', 'string'],
  992: ['array', 'hash-table', 'sliding-window', 'counting'],
  994: ['array', 'breadth-first-search', 'matrix'],
  997: ['array', 'hash-table', 'graph'],
  1007: ['array', 'greedy'],
  1009: ['math', 'bit-manipulation'],
  1011: ['array', 'binary-search'],
  1014: ['array', 'dynamic-programming'],
  1018: ['array', 'math'],
  1022: ['tree', 'depth-first-search', 'binary-tree'],
  1028: ['tree', 'depth-first-search', 'string', 'binary-tree'],
  1038: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  1039: ['array', 'math', 'dynamic-programming'],
  1052: ['array', 'sliding-window'],
  1061: ['array', 'hash-table', 'string', 'union-find'],
  1072: ['array', 'hash-table', 'matrix'],
  1079: ['hash-table', 'string', 'dynamic-programming', 'backtracking', 'counting'],
  1080: ['tree', 'depth-first-search', 'binary-tree'],
  1081: ['string', 'stack', 'greedy', 'monotonic-stack'],
  1092: ['string', 'dynamic-programming'],
  1105: ['array', 'dynamic-programming'],
  1106: ['string', 'stack', 'recursion'],
  1110: ['tree', 'depth-first-search', 'binary-tree'],
  1123: ['tree', 'depth-first-search', 'hash-table', 'breadth-first-search', 'binary-tree'],
  1128: ['array', 'hash-table', 'counting'],
  1140: ['array', 'math', 'dynamic-programming', 'game-theory'],
  1161: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  1190: ['string', 'stack'],
  1200: ['array', 'sorting'],
  1233: ['array', 'string', 'depth-first-search', 'trie'],
  1248: ['array', 'hash-table', 'math', 'sliding-window', 'prefix-sum'],
  1261: ['hash-table', 'tree', 'depth-first-search', 'breadth-first-search', 'design', 'binary-tree'],
  1262: ['array', 'dynamic-programming'],
  1266: ['array', 'math'],
  1267: ['array', 'counting', 'matrix'],

  // 68–998
  68:   ['string', 'simulation'],
  87:   ['string', 'dynamic-programming'],
  165:  ['two-pointers', 'string'],
  166:  ['hash-table', 'math', 'string'],
  171:  ['hash-table', 'math', 'string'],
  172:  ['math'],
  174:  ['array', 'dynamic-programming', 'matrix'],
  176:  ['database'],
  178:  ['database'],
  179:  ['array', 'math', 'string', 'sorting', 'greedy'],
  180:  ['database'],
  193:  ['shell'],
  214:  ['string', 'rolling-hash', 'string-matching'],
  241:  ['math', 'string', 'dynamic-programming', 'recursion', 'memoization'],
  299:  ['hash-table', 'string', 'counting'],
  310:  ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  319:  ['math', 'brain-teaser'],
  321:  ['array', 'two-pointers', 'greedy', 'stack', 'monotonic-stack'],
  324:  ['array', 'two-pointers', 'divide-and-conquer', 'sorting'],
  330:  ['array', 'greedy'],
  331:  ['string', 'stack', 'tree', 'binary-tree'],
  342:  ['math', 'bit-manipulation', 'recursion'],
  352:  ['array', 'binary-search', 'design', 'ordered-set'],
  367:  ['math', 'binary-search'],
  368:  ['array', 'math', 'dynamic-programming', 'sorting'],
  386:  ['depth-first-search', 'trie', 'stack', 'backtracking'],
  400:  ['math'],
  401:  ['bit-manipulation', 'backtracking'],
  405:  ['math'],
  407:  ['array', 'breadth-first-search', 'heap', 'matrix'],
  429:  ['tree', 'breadth-first-search'],
  432:  ['hash-table', 'linked-list', 'design', 'doubly-linked-list'],
  440:  ['trie'],
  467:  ['string', 'dynamic-programming'],
  477:  ['array', 'math', 'bit-manipulation'],
  479:  ['math'],
  500:  ['array', 'hash-table', 'string'],
  502:  ['array', 'greedy', 'sorting', 'heap'],
  508:  ['hash-table', 'tree', 'depth-first-search', 'binary-tree'],
  513:  ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  515:  ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  539:  ['array', 'math', 'string', 'sorting'],
  554:  ['array', 'hash-table'],
  558:  ['divide-and-conquer', 'tree'],
  564:  ['math', 'string'],
  590:  ['stack', 'tree', 'depth-first-search'],
  592:  ['math', 'string', 'simulation'],
  593:  ['array', 'math', 'geometry'],
  620:  ['database'],
  624:  ['array', 'greedy'],
  627:  ['database'],
  657:  ['string', 'simulation'],
  658:  ['array', 'two-pointers', 'binary-search', 'sorting', 'heap'],
  678:  ['string', 'dynamic-programming', 'stack', 'greedy'],
  679:  ['array', 'math', 'backtracking'],
  689:  ['array', 'sliding-window'],
  693:  ['bit-manipulation'],
  699:  ['array', 'segment-tree', 'ordered-set'],
  706:  ['array', 'hash-table', 'linked-list', 'design', 'hash-function'],
  707:  ['linked-list', 'design'],
  709:  ['string'],
  717:  ['array'],
  719:  ['array', 'two-pointers', 'binary-search', 'sorting'],
  725:  ['linked-list'],
  731:  ['array', 'binary-search', 'design', 'segment-tree', 'ordered-set'],
  744:  ['array', 'binary-search'],
  756:  ['array', 'hash-table', 'breadth-first-search'],
  757:  ['array', 'greedy', 'sorting'],
  761:  ['string', 'recursion'],
  762:  ['math', 'bit-manipulation'],
  781:  ['array', 'math', 'greedy'],
  788:  ['math'],
  796:  ['string', 'string-matching'],
  799:  ['array', 'dynamic-programming', 'simulation'],
  807:  ['array', 'greedy', 'matrix'],
  808:  ['math', 'dynamic-programming', 'probability-and-statistics'],
  812:  ['array', 'math', 'geometry'],
  818:  ['dynamic-programming'],
  821:  ['array', 'hash-table', 'string'],
  822:  ['array', 'hash-table', 'math'],
  825:  ['array', 'two-pointers', 'binary-search', 'sorting'],
  826:  ['array', 'two-pointers', 'binary-search', 'greedy', 'sorting'],
  827:  ['array', 'hash-table', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  829:  ['math'],
  832:  ['array', 'bit-manipulation', 'simulation'],
  834:  ['tree', 'depth-first-search', 'graph'],
  838:  ['array', 'two-pointers', 'string', 'dynamic-programming', 'simulation'],
  839:  ['string', 'depth-first-search', 'breadth-first-search', 'union-find'],
  840:  ['array', 'hash-table', 'math', 'matrix'],
  851:  ['array', 'depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  855:  ['design', 'ordered-set'],
  856:  ['string', 'stack', 'math'],
  857:  ['array', 'math', 'greedy', 'sorting', 'heap'],
  865:  ['tree', 'depth-first-search', 'binary-tree'],
  866:  ['math'],
  868:  ['bit-manipulation'],
  873:  ['array', 'hash-table', 'dynamic-programming'],
  874:  ['array', 'hash-table', 'simulation'],
  878:  ['math', 'binary-search', 'number-theory'],
  880:  ['array', 'string', 'stack'],
  885:  ['array', 'math', 'matrix', 'simulation'],
  889:  ['tree', 'hash-table', 'divide-and-conquer', 'binary-tree'],
  898:  ['array', 'math', 'dynamic-programming', 'bit-manipulation'],
  902:  ['array', 'math', 'string', 'dynamic-programming'],
  905:  ['array', 'two-pointers', 'sorting'],
  908:  ['array', 'math'],
  916:  ['array', 'hash-table', 'string'],
  928:  ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  944:  ['array', 'string', 'greedy'],
  955:  ['array', 'string', 'greedy'],
  960:  ['array', 'string', 'dynamic-programming'],
  961:  ['array', 'hash-table', 'math'],
  965:  ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  966:  ['array', 'hash-table', 'string', 'sorting'],
  981:  ['hash-table', 'string', 'binary-search', 'design'],
  995:  ['array', 'greedy', 'sliding-window', 'queue'],
  998:  ['tree', 'binary-tree'],
  1000: ['array', 'dynamic-programming'],
  1006: ['math', 'simulation'],
  1015: ['hash-table', 'math'],

  // 1277–1267 extras and 1277+
  1277: ['array', 'dynamic-programming', 'matrix'],
  1287: ['array'],
  1290: ['linked-list', 'math'],
  1295: ['array'],
  1298: ['array', 'breadth-first-search'],
  1304: ['array', 'math'],
  1305: ['tree', 'depth-first-search', 'binary-search-tree', 'sorting', 'binary-tree'],
  1310: ['array', 'bit-manipulation', 'prefix-sum'],
  1317: ['math'],
  1319: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  1323: ['math', 'greedy'],
  1331: ['array', 'hash-table', 'sorting'],
  1334: ['graph', 'shortest-path'],
  1339: ['tree', 'depth-first-search', 'binary-tree'],
  1346: ['array', 'hash-table', 'two-pointers', 'binary-search'],
  1352: ['array', 'math', 'design', 'queue'],
  1353: ['array', 'greedy', 'sorting', 'heap'],
  1358: ['hash-table', 'string', 'sliding-window'],
  1367: ['linked-list', 'tree', 'depth-first-search', 'binary-tree'],
  1368: ['array', 'breadth-first-search', 'graph', 'heap', 'matrix'],
  1371: ['hash-table', 'string', 'bit-manipulation', 'prefix-sum'],
  1380: ['array', 'hash-table', 'matrix'],
  1381: ['stack', 'design', 'array'],
  1382: ['tree', 'binary-search-tree', 'divide-and-conquer', 'binary-tree'],
  1390: ['math'],
  1392: ['string', 'string-matching', 'hash-function', 'rolling-hash'],
  1394: ['array', 'hash-table', 'sorting'],
  1395: ['array', 'math', 'dynamic-programming'],
  1399: ['hash-table', 'math', 'counting'],
  1400: ['hash-table', 'string', 'greedy', 'counting'],
  1405: ['string', 'greedy', 'heap'],
  1408: ['array', 'string', 'string-matching'],
  1410: ['hash-table', 'string'],
  1411: ['dynamic-programming'],
  1415: ['string', 'backtracking'],
  1422: ['string'],
  1432: ['math', 'greedy'],
  1437: ['array'],
  1438: ['array', 'queue', 'sliding-window', 'heap', 'monotonic-queue'],
  1450: ['array'],
  1455: ['array', 'string', 'string-matching'],
  1458: ['array', 'dynamic-programming'],
  1460: ['array'],
  1461: ['hash-table', 'string', 'bit-manipulation', 'rolling-hash', 'hash-function'],
  1462: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  1465: ['array', 'greedy', 'sorting'],
  1475: ['array', 'stack', 'monotonic-stack'],
  1482: ['array', 'binary-search'],
  1486: ['array', 'math', 'bit-manipulation'],
  1487: ['hash-table', 'string'],
  1488: ['array', 'hash-table', 'greedy', 'heap'],
  1493: ['array', 'dynamic-programming', 'sliding-window'],
  1497: ['array', 'hash-table', 'sorting'],
  1498: ['array', 'two-pointers', 'binary-search', 'sorting'],
  1503: ['array', 'simulation'],
  1504: ['array', 'dynamic-programming', 'matrix'],
  1508: ['array', 'two-pointers', 'binary-search', 'sorting'],
  1509: ['array', 'greedy', 'sorting'],
  1513: ['math', 'string', 'dynamic-programming'],
  1514: ['array', 'dynamic-programming', 'graph', 'heap', 'shortest-path', 'probability-and-statistics'],
  1518: ['math', 'simulation'],
  1523: ['math'],
  1524: ['array', 'math', 'prefix-sum'],
  1526: ['array', 'greedy', 'stack', 'monotonic-stack'],
  1529: ['string', 'greedy'],
  1530: ['tree', 'depth-first-search', 'binary-tree'],
  1534: ['array', 'enumeration'],
  1536: ['array', 'greedy', 'matrix'],
  1545: ['string', 'recursion', 'simulation'],
  1550: ['array'],
  1552: ['array', 'binary-search'],
  1568: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  1573: ['string', 'math'],
  1574: ['array', 'two-pointers', 'binary-search', 'stack', 'monotonic-stack'],
  1578: ['array', 'string', 'dynamic-programming', 'greedy'],
  1579: ['union-find', 'graph'],
  1582: ['array', 'matrix'],
  1590: ['array', 'hash-table', 'prefix-sum'],
  1593: ['hash-table', 'string', 'backtracking'],
  1598: ['stack', 'string', 'simulation'],
  1605: ['array', 'greedy', 'matrix'],
  1611: ['dynamic-programming', 'bit-manipulation'],
  1621: ['math', 'dynamic-programming', 'combinatorics'],
  1622: ['array', 'math', 'design', 'segment-tree'],
  1625: ['breadth-first-search', 'string'],
  1636: ['array', 'hash-table', 'sorting', 'counting'],
  1639: ['array', 'string', 'dynamic-programming'],
  1652: ['array'],
  1653: ['string', 'dynamic-programming', 'stack', 'greedy'],
  1671: ['array', 'binary-search', 'dynamic-programming', 'greedy'],
  1678: ['string'],
  1680: ['math', 'bit-manipulation', 'simulation'],
  1684: ['array', 'hash-table', 'string', 'bit-manipulation'],
  1689: ['string', 'greedy'],
  1695: ['array', 'hash-table', 'sliding-window'],
  1700: ['array', 'stack', 'queue', 'simulation'],
  1701: ['array', 'math', 'simulation'],
  1716: ['math'],
  1717: ['string', 'greedy', 'stack'],
  1718: ['array', 'backtracking'],
  1726: ['array', 'hash-table'],
  1727: ['array', 'greedy', 'matrix', 'sorting'],
  1733: ['array', 'greedy', 'union-find'],
  1749: ['array', 'dynamic-programming'],
  1751: ['array', 'binary-search', 'dynamic-programming', 'sorting', 'heap'],
  1752: ['array'],
  1758: ['string', 'greedy'],
  1760: ['array', 'binary-search'],
  1763: ['string'],
  1765: ['array', 'breadth-first-search', 'matrix'],
  1766: ['array', 'math', 'depth-first-search', 'tree', 'number-theory'],
  1768: ['two-pointers', 'string'],
  1769: ['array', 'string', 'prefix-sum'],
  1779: ['array'],
  1780: ['math'],
  1784: ['string'],
  1790: ['hash-table', 'string', 'counting'],
  1791: ['graph'],
  1792: ['greedy', 'heap', 'probability-and-statistics'],
  1799: ['array', 'math', 'dynamic-programming', 'bit-manipulation', 'backtracking'],
  1800: ['array'],
  1802: ['binary-search', 'greedy'],
  1813: ['two-pointers', 'string'],
  1823: ['array', 'math', 'recursion', 'queue', 'simulation'],
  1829: ['array', 'bit-manipulation', 'prefix-sum'],
  1844: ['string'],
  1857: ['hash-table', 'dynamic-programming', 'graph', 'topological-sort', 'memoization', 'counting'],
  1859: ['array', 'string', 'sorting'],
  1861: ['array', 'two-pointers', 'matrix', 'simulation'],
  1862: ['math', 'binary-search', 'dynamic-programming'],
  1863: ['array', 'math', 'bit-manipulation', 'backtracking', 'enumeration'],
  1865: ['array', 'hash-table', 'design'],
  1873: ['database'],
  1877: ['array', 'two-pointers', 'greedy', 'sorting'],
  1878: ['array', 'greedy', 'matrix'],
  1886: ['array', 'matrix'],
  1888: ['string', 'greedy', 'sliding-window'],
  1894: ['array', 'binary-search', 'prefix-sum', 'simulation'],
  1895: ['array', 'math', 'matrix'],
  1900: ['dynamic-programming'],
  1905: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  1910: ['string'],
  1911: ['array', 'dynamic-programming', 'greedy'],
  1912: ['array', 'hash-table', 'design', 'heap', 'ordered-set'],
  1920: ['array', 'simulation'],
  1922: ['math', 'counting'],
  1925: ['math', 'enumeration'],
  1930: ['hash-table', 'string', 'prefix-sum'],
  1931: ['dynamic-programming'],
  1935: ['hash-table', 'string'],
  1937: ['array', 'dynamic-programming'],
  1938: ['array', 'tree', 'depth-first-search', 'binary-search', 'trie', 'bit-manipulation'],
  1942: ['array', 'hash-table', 'heap'],
  1945: ['string', 'simulation'],
  1948: ['hash-table', 'string', 'trie', 'depth-first-search'],
  1957: ['string', 'greedy'],
  1963: ['two-pointers', 'string', 'greedy', 'stack'],
  1967: ['string'],
  1970: ['array', 'binary-search', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  1971: ['breadth-first-search', 'depth-first-search', 'union-find', 'graph'],
  1975: ['array', 'greedy', 'matrix'],
  1976: ['dynamic-programming', 'graph', 'topological-sort', 'shortest-path'],
  1980: ['array', 'hash-table', 'string', 'backtracking'],
  1994: ['array', 'math', 'dynamic-programming', 'bit-manipulation', 'number-theory'],
  1995: ['array', 'hash-table', 'enumeration'],
  2007: ['array', 'hash-table'],
  2008: ['array', 'binary-search', 'dynamic-programming', 'sorting'],
  2009: ['array', 'binary-search', 'sliding-window'],
  2011: ['string', 'simulation'],
  2014: ['string', 'backtracking', 'greedy'],
  2016: ['array'],
  2017: ['array', 'matrix', 'simulation'],
  2022: ['array', 'matrix', 'simulation'],
  2028: ['array', 'math', 'simulation'],
  2033: ['array', 'math', 'greedy', 'matrix'],
  2040: ['array', 'binary-search', 'sorting'],
  2043: ['array', 'hash-table', 'design', 'simulation'],
  2044: ['array', 'bit-manipulation', 'backtracking', 'enumeration'],
  2045: ['breadth-first-search', 'graph', 'shortest-path'],
  2048: ['math'],
  2053: ['array', 'hash-table', 'string'],
  2054: ['array', 'binary-search', 'dynamic-programming', 'sorting', 'heap'],
  2058: ['array', 'linked-list', 'two-pointers'],
  2064: ['array', 'binary-search'],
  2070: ['array', 'binary-search', 'sorting'],
  2071: ['array', 'binary-search', 'greedy', 'sorting', 'heap'],
  2081: ['math'],
  2090: ['array', 'sliding-window'],
  2091: ['array', 'greedy'],
  2092: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph', 'sorting'],
  2094: ['array', 'hash-table', 'math', 'enumeration'],
  2096: ['tree', 'string', 'depth-first-search', 'binary-tree'],
  2097: ['depth-first-search', 'graph', 'eulerian-circuit'],
  2099: ['array', 'sorting', 'heap'],
  2106: ['array', 'binary-search', 'sliding-window', 'prefix-sum'],
  2109: ['array', 'string', 'simulation'],
  2110: ['array', 'dynamic-programming'],
  2115: ['array', 'hash-table', 'breadth-first-search', 'graph', 'topological-sort'],
  2116: ['string', 'greedy', 'stack'],
  2125: ['array', 'math', 'matrix'],
  2127: ['depth-first-search', 'graph', 'topological-sort'],
  2131: ['array', 'hash-table', 'string', 'greedy', 'counting'],
  2134: ['array', 'greedy', 'sliding-window'],
  2138: ['string', 'simulation'],
  2140: ['array', 'dynamic-programming'],
  2141: ['array', 'binary-search', 'greedy', 'sorting'],
  2145: ['array', 'prefix-sum'],
  2147: ['math', 'dynamic-programming'],
  2154: ['array', 'hash-table', 'simulation'],
  2161: ['array', 'two-pointers', 'sorting'],
  2163: ['array', 'dynamic-programming', 'sorting', 'heap'],
  2169: ['math', 'simulation'],
  2176: ['array', 'hash-table', 'counting'],
  2179: ['array', 'binary-indexed-tree', 'merge-sort'],
  2181: ['linked-list', 'simulation'],
  2182: ['string', 'greedy', 'heap', 'counting'],
  2185: ['array', 'string', 'prefix-sum'],
  2191: ['array', 'hash-table', 'sorting'],
  2192: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  2196: ['array', 'hash-table', 'tree', 'binary-tree'],
  2197: ['array', 'math', 'stack', 'number-theory'],
  2200: ['array'],
  2206: ['array', 'hash-table', 'sorting', 'bit-manipulation', 'counting'],
  2210: ['array', 'counting'],
  2211: ['array', 'stack', 'simulation'],
  2220: ['bit-manipulation'],
  2221: ['array', 'math', 'simulation'],
  2225: ['array', 'hash-table', 'sorting', 'counting'],
  2226: ['array', 'binary-search'],
  2236: ['tree', 'binary-tree'],
  2257: ['array', 'matrix', 'simulation'],
  2264: ['string'],
  2270: ['array', 'prefix-sum'],
  2271: ['array', 'binary-search', 'sliding-window'],
  2273: ['array', 'hash-table', 'string', 'sorting'],
  2275: ['array', 'hash-table', 'bit-manipulation', 'counting', 'enumeration'],
  2285: ['array', 'greedy', 'graph', 'sorting', 'heap'],
  2290: ['array', 'breadth-first-search', 'graph', 'heap', 'matrix', 'shortest-path'],
  2294: ['array', 'binary-search', 'greedy', 'sorting'],
  2300: ['array', 'two-pointers', 'binary-search', 'sorting'],
  2302: ['array', 'binary-search', 'prefix-sum', 'sliding-window'],
  2311: ['array', 'binary-search', 'dynamic-programming', 'greedy'],
  2322: ['array', 'bit-manipulation', 'tree', 'depth-first-search'],
  2326: ['array', 'linked-list', 'matrix', 'simulation'],
  2327: ['dynamic-programming'],
  2331: ['tree', 'depth-first-search', 'binary-tree'],
  2337: ['two-pointers', 'string'],
  2338: ['math', 'dynamic-programming', 'combinatorics', 'number-theory'],
  2342: ['array', 'hash-table', 'sorting'],
  2344: ['array', 'math', 'number-theory'],
  2348: ['array', 'math', 'prefix-sum'],
  2349: ['hash-table', 'design'],
  2353: ['hash-table', 'design', 'heap', 'ordered-set'],
  2359: ['graph'],
  2364: ['array', 'hash-table'],
  2369: ['array', 'dynamic-programming'],
  2370: ['array', 'hash-table', 'dynamic-programming'],
  2375: ['string', 'stack', 'greedy'],
  2379: ['string', 'sliding-window'],
  2381: ['array', 'binary-search', 'difference-array'],
  2389: ['array', 'binary-search', 'greedy', 'prefix-sum', 'sorting'],
  2392: ['array', 'matrix', 'graph', 'topological-sort'],
  2400: ['math', 'dynamic-programming', 'combinatorics'],
  2401: ['array', 'bit-manipulation', 'sliding-window'],
  2402: ['array', 'greedy', 'sorting', 'heap'],
  2406: ['array', 'greedy', 'sorting', 'heap', 'prefix-sum'],
  2409: ['math'],
  2410: ['array', 'two-pointers', 'greedy', 'sorting'],
  2411: ['array', 'bit-manipulation', 'sliding-window'],
  2415: ['tree', 'depth-first-search', 'binary-tree'],
  2416: ['array', 'string', 'trie', 'counting'],
  2418: ['array', 'hash-table', 'string', 'sorting'],
  2419: ['array', 'bit-manipulation'],
  2425: ['array', 'hash-table', 'bit-manipulation'],
  2429: ['bit-manipulation', 'greedy'],
  2434: ['string', 'stack', 'greedy', 'simulation'],
  2435: ['array', 'dynamic-programming', 'matrix'],
  2438: ['array', 'bit-manipulation', 'prefix-sum'],
  2440: ['tree', 'depth-first-search', 'graph'],
  2444: ['array', 'sliding-window', 'monotonic-stack'],
  2458: ['array', 'tree', 'depth-first-search', 'binary-tree'],
  2460: ['array', 'simulation'],
  2461: ['array', 'hash-table', 'sliding-window'],
  2463: ['array', 'dynamic-programming'],
  2466: ['dynamic-programming'],
  2467: ['array', 'depth-first-search', 'tree', 'graph'],
  2471: ['tree', 'breadth-first-search', 'binary-tree', 'sorting'],
  2490: ['string'],
  2491: ['array', 'hash-table', 'two-pointers', 'greedy', 'sorting'],
  2493: ['breadth-first-search', 'union-find', 'graph'],
  2501: ['array', 'hash-table', 'binary-search', 'dynamic-programming'],
  2503: ['array', 'breadth-first-search', 'union-find', 'sorting', 'matrix'],
  2508: ['graph'],
  2509: ['tree', 'math', 'binary-lifting', 'graph'],
  2516: ['hash-table', 'string', 'sliding-window'],
  2523: ['math', 'number-theory'],
  2528: ['array', 'binary-search', 'greedy', 'heap'],
  2529: ['array', 'binary-search', 'counting'],
  2530: ['array', 'greedy', 'heap'],
  2536: ['array', 'matrix', 'prefix-sum'],
  2537: ['array', 'hash-table', 'sliding-window'],
  2551: ['array', 'binary-search', 'greedy', 'sorting'],
  2553: ['array', 'simulation'],
  2554: ['array', 'hash-table', 'binary-search', 'greedy', 'sorting'],
  2558: ['array', 'greedy', 'heap', 'simulation'],
  2559: ['array', 'string', 'binary-search', 'prefix-sum'],
  2560: ['array', 'binary-search'],
  2561: ['array', 'greedy'],
  2563: ['array', 'two-pointers', 'binary-search', 'sorting'],
  2566: ['math', 'greedy'],
  2570: ['array', 'hash-table', 'two-pointers'],
  2572: ['array', 'math', 'dynamic-programming', 'bit-manipulation', 'number-theory'],
  2577: ['array', 'breadth-first-search', 'graph', 'heap', 'matrix', 'shortest-path'],
  2579: ['math'],
  2582: ['array', 'simulation'],
  2583: ['tree', 'breadth-first-search', 'sorting', 'binary-tree', 'heap'],
  2593: ['array', 'greedy', 'heap', 'simulation'],
  2594: ['array', 'binary-search'],
  2598: ['array', 'hash-table', 'greedy'],
  2601: ['array', 'binary-search', 'greedy', 'number-theory'],
  2609: ['string'],
  2616: ['array', 'binary-search', 'greedy'],
  2625: ['javascript'],
  2626: ['javascript'],
  2639: ['array', 'matrix', 'simulation'],
  2640: ['array', 'prefix-sum'],
  2641: ['hash-table', 'tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  2645: ['string', 'greedy'],
  2654: ['array', 'math'],
  2657: ['array', 'hash-table', 'bit-manipulation', 'prefix-sum'],
  2658: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  2661: ['array', 'hash-table', 'matrix'],
  2666: ['javascript'],
  2667: ['javascript'],
  2678: ['array', 'string', 'simulation'],
  2683: ['array', 'bit-manipulation', 'prefix-sum'],
  2684: ['array', 'dynamic-programming', 'matrix'],
  2685: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  2696: ['string', 'stack', 'simulation'],
  2698: ['math', 'backtracking'],
  2699: ['graph', 'shortest-path'],
  2707: ['array', 'hash-table', 'string', 'dynamic-programming', 'trie'],
  2718: ['array', 'hash-table', 'matrix', 'simulation'],
  2749: ['array', 'bit-manipulation'],
  2751: ['array', 'stack', 'simulation'],
  2762: ['array', 'hash-table', 'queue', 'sliding-window', 'ordered-set', 'monotonic-queue'],
  2765: ['array'],
  2779: ['array', 'binary-search', 'sorting'],
  2780: ['array', 'hash-table', 'sorting'],
  2785: ['string', 'sorting'],
  2787: ['math', 'dynamic-programming'],
  2799: ['array', 'hash-table', 'sliding-window', 'counting'],
  2807: ['array', 'math', 'linked-list', 'number-theory'],
  2818: ['array', 'math', 'dynamic-programming', 'greedy', 'stack', 'sorting', 'monotonic-stack', 'number-theory'],
  2825: ['two-pointers', 'string'],
  2843: ['math', 'enumeration'],
  2845: ['array', 'hash-table', 'math', 'prefix-sum'],
  2872: ['tree', 'depth-first-search', 'dynamic-programming'],
  2873: ['array'],
  2874: ['array'],
  2889: ['database'],
  2894: ['math'],
  2900: ['array', 'string', 'greedy', 'dynamic-programming'],
  2901: ['array', 'string', 'greedy', 'dynamic-programming'],
  2906: ['array', 'math', 'matrix', 'prefix-sum'],
  2909: ['array', 'sorting'],
  2914: ['string', 'greedy'],
  2916: ['array', 'dynamic-programming'],
  2918: ['array', 'greedy'],
  2924: ['graph'],
  2929: ['math', 'combinatorics'],
  2930: ['math', 'dynamic-programming', 'string', 'counting'],
  2938: ['array', 'two-pointers', 'greedy'],
  2940: ['array', 'binary-search', 'stack', 'heap', 'monotonic-stack'],
  2942: ['array', 'string'],
  2943: ['math', 'matrix', 'enumeration'],
  2948: ['array', 'greedy', 'sorting', 'ordered-set'],
  2962: ['array', 'sliding-window'],
  2965: ['array', 'hash-table', 'matrix'],
  2966: ['array', 'greedy', 'sorting'],
  2975: ['array', 'math', 'matrix', 'enumeration'],
  2976: ['array', 'string', 'dynamic-programming', 'graph', 'shortest-path'],
  2977: ['array', 'string', 'dynamic-programming', 'graph', 'shortest-path'],
  2980: ['array', 'bit-manipulation'],
  2981: ['hash-table', 'string', 'sliding-window'],
  2999: ['math', 'string', 'dynamic-programming'],
  3000: ['array', 'math', 'sorting'],
  3001: ['array', 'enumeration'],
  3003: ['dynamic-programming', 'string', 'bit-manipulation'],
  3005: ['array', 'hash-table', 'counting'],
  3010: ['array'],
  3011: ['array', 'bit-manipulation', 'sorting'],
  3013: ['array', 'binary-search', 'sliding-window'],
  3016: ['string', 'greedy', 'sorting', 'hash-table', 'counting'],
  3021: ['math', 'game-theory'],
  3024: ['math', 'sorting'],
  3025: ['array', 'math', 'sorting', 'geometry', 'enumeration'],
  3027: ['array', 'math', 'sorting', 'geometry', 'enumeration'],
  3042: ['array', 'string', 'trie', 'hash-function', 'rolling-hash'],
  3043: ['array', 'string', 'trie', 'hash-function', 'rolling-hash'],
  3047: ['array', 'math', 'sorting', 'enumeration'],
  3066: ['array', 'greedy', 'heap'],
  3068: ['array', 'dynamic-programming', 'greedy', 'tree', 'depth-first-search'],
  3070: ['array', 'matrix', 'prefix-sum'],
  3074: ['array', 'greedy'],
  3085: ['array', 'hash-table', 'string', 'greedy', 'sorting'],
  3097: ['array', 'bit-manipulation', 'sliding-window'],
  3100: ['math', 'simulation'],
  3105: ['array'],
  3108: ['array', 'union-find', 'graph'],
  3116: ['array', 'math', 'binary-search', 'number-theory', 'combinatorics'],
  3122: ['array', 'dynamic-programming', 'matrix'],
  3129: ['array', 'dynamic-programming'],
  3130: ['array', 'dynamic-programming'],
  3133: ['array', 'bit-manipulation'],
  3136: ['string'],
  3147: ['array', 'dynamic-programming'],
  3149: ['array', 'dynamic-programming', 'bitmask'],
  3151: ['array'],
  3152: ['array', 'binary-search', 'prefix-sum'],
  3160: ['array', 'hash-table', 'simulation'],
  3163: ['string'],
  3169: ['array', 'sorting'],
  3170: ['string', 'stack', 'greedy', 'simulation'],
  3174: ['string', 'simulation'],
  3186: ['array', 'hash-table', 'dynamic-programming', 'sorting'],
  3190: ['array', 'math'],
  3191: ['array', 'bit-manipulation', 'greedy', 'queue'],
  3192: ['array', 'dynamic-programming', 'greedy'],
  3195: ['array', 'matrix'],
  3197: ['array', 'matrix'],
  3201: ['array', 'dynamic-programming'],
  3202: ['array', 'dynamic-programming'],
  3203: ['tree', 'depth-first-search', 'breadth-first-search', 'graph'],
  3208: ['array', 'sliding-window'],
  3212: ['array', 'matrix', 'prefix-sum'],
  3217: ['array', 'hash-table', 'linked-list'],
  3223: ['string', 'hash-table', 'counting'],
  3227: ['math', 'game-theory', 'string'],
  3228: ['array', 'greedy', 'stack', 'simulation'],
  3234: ['array', 'string', 'sliding-window'],
  3243: ['breadth-first-search', 'graph'],
  3254: ['array', 'sliding-window'],
  3264: ['array', 'math', 'simulation'],
  3272: ['hash-table', 'math', 'counting', 'enumeration', 'number-theory'],
  3289: ['array', 'hash-table', 'math'],
  3296: ['array', 'math', 'greedy', 'heap'],
  3304: ['math', 'simulation'],
  3306: ['hash-table', 'string', 'sliding-window'],
  3307: ['math', 'bit-manipulation', 'recursion'],
  3310: ['array', 'depth-first-search', 'union-find', 'graph'],
  3315: ['array', 'bit-manipulation'],
  3318: ['array', 'hash-table', 'sliding-window', 'heap', 'ordered-set'],
  3321: ['array', 'hash-table', 'sliding-window', 'heap', 'ordered-set'],
  3330: ['string', 'counting'],
  3333: ['string', 'dynamic-programming'],
  3335: ['hash-table', 'math', 'string', 'dynamic-programming', 'counting'],
  3337: ['hash-table', 'math', 'string', 'dynamic-programming', 'counting', 'matrix'],
  3341: ['array', 'graph', 'heap', 'shortest-path'],
  3342: ['array', 'graph', 'heap', 'shortest-path'],
  3343: ['math', 'dynamic-programming', 'combinatorics', 'counting', 'number-theory'],
  3346: ['array', 'binary-search', 'sliding-window', 'prefix-sum'],
  3347: ['array', 'binary-search', 'sliding-window', 'prefix-sum'],
  3349: ['array'],
  3350: ['array'],
  3354: ['array', 'sliding-window'],
  3355: ['array', 'prefix-sum'],
  3356: ['array', 'binary-search', 'prefix-sum'],
  3362: ['array', 'greedy', 'heap'],
  3363: ['array', 'dynamic-programming', 'matrix'],
  3370: ['math', 'bit-manipulation'],
  3372: ['tree', 'depth-first-search', 'breadth-first-search', 'graph'],
  3373: ['tree', 'depth-first-search', 'breadth-first-search', 'graph'],
  3375: ['array', 'hash-table'],
  3379: ['array', 'simulation'],
  3381: ['array', 'sliding-window', 'prefix-sum'],
  3392: ['array'],
  3394: ['array', 'greedy', 'sorting'],
  3396: ['array', 'hash-table', 'sorting'],
  3397: ['array', 'greedy', 'sorting', 'heap'],
  3403: ['array', 'string', 'simulation'],
  3405: ['math', 'counting', 'combinatorics'],
  3408: ['hash-table', 'design', 'heap', 'ordered-set'],
  3423: ['array'],
  3432: ['array', 'math'],
  3433: ['array', 'sorting', 'simulation'],
  3439: ['array', 'greedy', 'sorting'],
  3440: ['array', 'greedy', 'sorting'],
  3442: ['hash-table', 'string', 'counting'],
  3443: ['array', 'hash-table', 'math', 'greedy'],
  3445: ['hash-table', 'string', 'sliding-window'],
  3446: ['array', 'sorting', 'matrix'],
  3453: ['math', 'binary-search'],
  3454: ['math', 'binary-search'],
  3459: ['array', 'dynamic-programming', 'matrix'],
  3461: ['string', 'math', 'simulation'],
  3477: ['array', 'binary-search', 'sliding-window', 'queue'],
  3479: ['array', 'binary-search', 'sliding-window', 'queue'],
  3480: ['array', 'segment-tree'],
  3484: ['array', 'hash-table', 'design', 'matrix'],
  3487: ['array', 'dynamic-programming', 'sliding-window'],
  3494: ['array', 'math', 'heap'],
  3495: ['array', 'math', 'bit-manipulation'],
  3507: ['array', 'linked-list', 'simulation'],
  3508: ['array', 'hash-table', 'queue', 'design'],
  3510: ['array', 'linked-list', 'simulation'],
  3512: ['array', 'math'],
  3516: ['array', 'simulation'],
  3531: ['array', 'sorting', 'simulation'],
  3539: ['array', 'math', 'dynamic-programming', 'bit-manipulation', 'combinatorics'],
  3541: ['hash-table', 'string', 'counting'],
  3542: ['array', 'greedy', 'simulation'],
  3562: ['array', 'dynamic-programming', 'greedy', 'sorting'],
  3567: ['array', 'sliding-window', 'matrix'],
  3573: ['array', 'dynamic-programming'],
  3577: ['math', 'counting', 'combinatorics'],
  3578: ['array', 'binary-search', 'dynamic-programming', 'sliding-window'],
  3583: ['array', 'math', 'counting'],
  3600: ['graph'],
  3606: ['array', 'string', 'simulation'],
  3607: ['array', 'design', 'simulation'],
  3623: ['array', 'math', 'sorting', 'geometry', 'counting'],
  3625: ['array', 'math', 'sorting', 'geometry', 'counting'],
  3634: ['array', 'greedy'],
  3637: ['array', 'simulation'],
  3640: ['array', 'dynamic-programming'],
  3643: ['array', 'dynamic-programming', 'matrix'],
  3651: ['dynamic-programming', 'graph', 'shortest-path'],
  3652: ['array', 'dynamic-programming'],
  3713: ['string'],
  3714: ['string'],
  3719: ['array'],
  3721: ['array', 'dynamic-programming'],
}

/** Return tags for a given problem number. Returns [] if not in the map. */
export function getTagsForProblem(number: number): Tag[] {
  return PROBLEM_TAGS[number] ?? []
}

/**
 * Return all tags sorted by frequency descending.
 * Each entry: { tag, label, count }
 */
export function getAllTags(): { tag: Tag; label: string; count: number }[] {
  const counts: Record<string, number> = {}
  for (const tags of Object.values(PROBLEM_TAGS)) {
    for (const tag of tags) {
      counts[tag] = (counts[tag] ?? 0) + 1
    }
  }
  return Object.entries(counts)
    .map(([tag, count]) => ({
      tag,
      label: TAG_LABELS[tag] ?? tag.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      count,
    }))
    .sort((a, b) => b.count - a.count)
}

/** Return all problem numbers that have a given tag */
export function getProblemNumbersByTag(tag: Tag): number[] {
  return Object.entries(PROBLEM_TAGS)
    .filter(([, tags]) => tags.includes(tag))
    .map(([n]) => parseInt(n))
    .sort((a, b) => a - b)
}
