// Static map: LeetCode problem number → topic tags
// Used to power /topics/[tag] pages and tag chips on detail pages

export type Tag = string

export const TAG_LABELS: Record<string, string> = {
  'array': 'Array',
  'string': 'String',
  'dynamic-programming': 'Dynamic Programming',
  'tree': 'Tree',
  'binary-search': 'Binary Search',
  'hash-table': 'Hash Table',
  'math': 'Math',
  'two-pointers': 'Two Pointers',
  'depth-first-search': 'Depth-First Search',
  'breadth-first-search': 'Breadth-First Search',
  'sorting': 'Sorting',
  'greedy': 'Greedy',
  'stack': 'Stack',
  'linked-list': 'Linked List',
  'backtracking': 'Backtracking',
  'sliding-window': 'Sliding Window',
  'matrix': 'Matrix',
  'prefix-sum': 'Prefix Sum',
  'bit-manipulation': 'Bit Manipulation',
  'heap': 'Heap (Priority Queue)',
  'monotonic-stack': 'Monotonic Stack',
  'graph': 'Graph',
  'union-find': 'Union Find',
  'trie': 'Trie',
  'design': 'Design',
  'recursion': 'Recursion',
  'queue': 'Queue',
  'binary-tree': 'Binary Tree',
  'binary-search-tree': 'Binary Search Tree',
  'divide-and-conquer': 'Divide and Conquer',
  'simulation': 'Simulation',
  'counting': 'Counting',
  'memoization': 'Memoization',
  'topological-sort': 'Topological Sort',
  'segment-tree': 'Segment Tree',
  'binary-indexed-tree': 'Binary Indexed Tree',
  'geometry': 'Geometry',
  'game-theory': 'Game Theory',
  'number-theory': 'Number Theory',
  'string-matching': 'String Matching',
  'ordered-set': 'Ordered Set',
  'rolling-hash': 'Rolling Hash',
}

// Problem number → tags
export const PROBLEM_TAGS: Record<number, Tag[]> = {
  1:   ['array', 'hash-table'],
  2:   ['linked-list', 'math', 'recursion'],
  3:   ['string', 'sliding-window', 'hash-table'],
  4:   ['array', 'binary-search', 'divide-and-conquer'],
  5:   ['string', 'dynamic-programming'],
  6:   ['string', 'simulation'],
  7:   ['math'],
  8:   ['string', 'math'],
  9:   ['math'],
  10:  ['string', 'dynamic-programming', 'recursion'],
  11:  ['array', 'two-pointers', 'greedy'],
  12:  ['math', 'string'],
  13:  ['math', 'string'],
  14:  ['string'],
  15:  ['array', 'two-pointers', 'sorting'],
  16:  ['array', 'two-pointers', 'sorting'],
  17:  ['string', 'backtracking'],
  18:  ['array', 'two-pointers', 'sorting'],
  19:  ['linked-list', 'two-pointers'],
  20:  ['string', 'stack'],
  21:  ['linked-list', 'recursion'],
  22:  ['string', 'backtracking', 'dynamic-programming'],
  23:  ['linked-list', 'heap', 'divide-and-conquer'],
  24:  ['linked-list', 'recursion'],
  25:  ['linked-list', 'recursion'],
  26:  ['array', 'two-pointers'],
  27:  ['array', 'two-pointers'],
  28:  ['string', 'two-pointers', 'string-matching'],
  29:  ['math', 'bit-manipulation'],
  30:  ['string', 'hash-table', 'sliding-window'],
  31:  ['array'],
  32:  ['string', 'stack', 'dynamic-programming'],
  33:  ['array', 'binary-search'],
  34:  ['array', 'binary-search'],
  35:  ['array', 'binary-search'],
  36:  ['array', 'hash-table', 'matrix'],
  37:  ['array', 'backtracking', 'matrix'],
  38:  ['string'],
  39:  ['array', 'backtracking'],
  40:  ['array', 'backtracking'],
  41:  ['array', 'hash-table'],
  42:  ['array', 'two-pointers', 'dynamic-programming', 'stack', 'monotonic-stack'],
  43:  ['math', 'string'],
  44:  ['string', 'dynamic-programming', 'greedy'],
  45:  ['array', 'dynamic-programming', 'greedy', 'breadth-first-search'],
  46:  ['array', 'backtracking'],
  47:  ['array', 'backtracking'],
  48:  ['array', 'math', 'matrix'],
  49:  ['array', 'hash-table', 'string', 'sorting'],
  50:  ['math', 'recursion'],
  51:  ['array', 'backtracking'],
  52:  ['array', 'backtracking'],
  53:  ['array', 'dynamic-programming', 'divide-and-conquer'],
  54:  ['array', 'matrix', 'simulation'],
  55:  ['array', 'dynamic-programming', 'greedy'],
  56:  ['array', 'sorting'],
  57:  ['array'],
  58:  ['array', 'string'],
  59:  ['array', 'matrix', 'simulation'],
  60:  ['math', 'recursion'],
  61:  ['linked-list', 'two-pointers'],
  62:  ['math', 'dynamic-programming'],
  63:  ['array', 'dynamic-programming'],
  64:  ['array', 'dynamic-programming', 'matrix'],
  66:  ['array', 'math'],
  67:  ['math', 'string', 'bit-manipulation'],
  69:  ['math', 'binary-search'],
  70:  ['math', 'dynamic-programming', 'memoization'],
  71:  ['string', 'stack'],
  72:  ['string', 'dynamic-programming'],
  73:  ['array', 'hash-table', 'matrix'],
  74:  ['array', 'binary-search', 'matrix'],
  75:  ['array', 'two-pointers', 'sorting'],
  76:  ['string', 'hash-table', 'sliding-window'],
  77:  ['array', 'backtracking'],
  78:  ['array', 'backtracking', 'bit-manipulation'],
  79:  ['array', 'backtracking', 'matrix', 'depth-first-search'],
  80:  ['array', 'two-pointers'],
  82:  ['linked-list', 'two-pointers'],
  83:  ['linked-list'],
  84:  ['array', 'stack', 'monotonic-stack'],
  85:  ['array', 'stack', 'dynamic-programming', 'matrix'],
  86:  ['linked-list', 'two-pointers'],
  88:  ['array', 'two-pointers', 'sorting'],
  90:  ['array', 'backtracking', 'bit-manipulation'],
  91:  ['string', 'dynamic-programming'],
  92:  ['linked-list'],
  94:  ['tree', 'depth-first-search', 'binary-tree', 'stack'],
  95:  ['dynamic-programming', 'binary-tree'],
  96:  ['math', 'dynamic-programming', 'binary-search-tree'],
  97:  ['string', 'dynamic-programming'],
  98:  ['tree', 'depth-first-search', 'binary-search-tree'],
  99:  ['tree', 'depth-first-search', 'binary-search-tree'],
  100: ['tree', 'depth-first-search', 'binary-tree'],
  101: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  102: ['tree', 'breadth-first-search', 'binary-tree'],
  103: ['tree', 'breadth-first-search', 'binary-tree', 'stack'],
  104: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  105: ['array', 'hash-table', 'tree', 'binary-tree', 'divide-and-conquer'],
  106: ['array', 'hash-table', 'tree', 'binary-tree', 'divide-and-conquer'],
  107: ['tree', 'breadth-first-search', 'binary-tree'],
  108: ['array', 'tree', 'binary-search-tree', 'binary-tree', 'divide-and-conquer'],
  110: ['tree', 'depth-first-search', 'binary-tree'],
  111: ['tree', 'depth-first-search', 'binary-tree', 'breadth-first-search'],
  112: ['tree', 'depth-first-search', 'binary-tree'],
  113: ['tree', 'depth-first-search', 'backtracking', 'binary-tree'],
  114: ['linked-list', 'stack', 'tree', 'depth-first-search', 'binary-tree'],
  116: ['linked-list', 'tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  118: ['array', 'dynamic-programming'],
  119: ['array', 'dynamic-programming'],
  120: ['array', 'dynamic-programming'],
  121: ['array', 'dynamic-programming'],
  122: ['array', 'dynamic-programming', 'greedy'],
  123: ['array', 'dynamic-programming'],
  124: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  125: ['two-pointers', 'string'],
  126: ['hash-table', 'string', 'backtracking', 'breadth-first-search', 'graph'],
  127: ['hash-table', 'string', 'breadth-first-search', 'graph'],
  128: ['array', 'hash-table', 'union-find'],
  129: ['tree', 'depth-first-search', 'binary-tree'],
  130: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  131: ['string', 'dynamic-programming', 'backtracking'],
  132: ['string', 'dynamic-programming'],
  133: ['hash-table', 'depth-first-search', 'breadth-first-search', 'graph'],
  134: ['array', 'greedy'],
  135: ['array', 'greedy'],
  136: ['array', 'bit-manipulation'],
  137: ['array', 'bit-manipulation'],
  139: ['array', 'hash-table', 'string', 'dynamic-programming', 'trie'],
  140: ['hash-table', 'string', 'dynamic-programming', 'backtracking', 'trie'],
  141: ['hash-table', 'linked-list', 'two-pointers'],
  142: ['hash-table', 'linked-list', 'two-pointers'],
  143: ['linked-list', 'two-pointers', 'stack', 'recursion'],
  144: ['stack', 'tree', 'depth-first-search', 'binary-tree'],
  145: ['stack', 'tree', 'depth-first-search', 'binary-tree'],
  146: ['hash-table', 'linked-list', 'design'],
  148: ['linked-list', 'two-pointers', 'divide-and-conquer', 'sorting'],
  150: ['array', 'math', 'stack'],
  151: ['two-pointers', 'string'],
  152: ['array', 'dynamic-programming'],
  153: ['array', 'binary-search'],
  154: ['array', 'binary-search'],
  155: ['stack', 'design'],
  160: ['linked-list', 'hash-table', 'two-pointers'],
  162: ['array', 'binary-search'],
  167: ['array', 'two-pointers', 'binary-search'],
  168: ['math', 'string'],
  169: ['array', 'hash-table', 'divide-and-conquer', 'sorting', 'counting'],
  189: ['array', 'math', 'two-pointers'],
  190: ['bit-manipulation', 'divide-and-conquer'],
  191: ['bit-manipulation'],
  198: ['array', 'dynamic-programming'],
  199: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  200: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  201: ['bit-manipulation'],
  202: ['hash-table', 'math', 'two-pointers'],
  203: ['linked-list', 'recursion'],
  205: ['hash-table', 'string'],
  206: ['linked-list', 'recursion'],
  207: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  208: ['hash-table', 'string', 'design', 'trie'],
  209: ['array', 'binary-search', 'sliding-window', 'prefix-sum'],
  210: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  211: ['string', 'depth-first-search', 'design', 'trie'],
  212: ['array', 'string', 'backtracking', 'matrix', 'trie'],
  213: ['array', 'dynamic-programming'],
  215: ['array', 'divide-and-conquer', 'sorting', 'heap'],
  216: ['array', 'backtracking'],
  217: ['array', 'hash-table', 'sorting'],
  218: ['array', 'divide-and-conquer', 'binary-search', 'sorting', 'heap', 'ordered-set'],
  219: ['array', 'hash-table', 'sliding-window'],
  220: ['array', 'sorting', 'sliding-window', 'ordered-set'],
  221: ['array', 'dynamic-programming', 'matrix'],
  222: ['tree', 'depth-first-search', 'binary-search', 'binary-tree'],
  224: ['string', 'stack', 'recursion'],
  226: ['tree', 'depth-first-search', 'binary-tree'],
  227: ['math', 'string', 'stack'],
  229: ['array', 'hash-table', 'sorting', 'counting'],
  230: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  231: ['math', 'bit-manipulation'],
  232: ['stack', 'design', 'queue'],
  234: ['linked-list', 'two-pointers', 'stack', 'recursion'],
  235: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  236: ['tree', 'depth-first-search', 'binary-tree'],
  237: ['linked-list'],
  238: ['array', 'prefix-sum'],
  239: ['array', 'queue', 'sliding-window', 'heap', 'monotonic-stack'],
  240: ['array', 'binary-search', 'divide-and-conquer', 'matrix'],
  242: ['hash-table', 'string', 'sorting'],
  257: ['tree', 'depth-first-search', 'string', 'backtracking', 'binary-tree'],
  260: ['array', 'bit-manipulation'],
  263: ['math'],
  264: ['hash-table', 'math', 'dynamic-programming', 'heap'],
  268: ['array', 'hash-table', 'math', 'bit-manipulation', 'sorting'],
  269: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort'],
  273: ['math', 'string', 'recursion'],
  278: ['array', 'binary-search'],
  279: ['math', 'dynamic-programming', 'breadth-first-search'],
  283: ['array', 'two-pointers'],
  287: ['array', 'two-pointers', 'binary-search', 'bit-manipulation', 'hash-table'],
  289: ['array', 'matrix', 'simulation'],
  295: ['two-pointers', 'design', 'sorting', 'heap'],
  297: ['string', 'tree', 'depth-first-search', 'breadth-first-search', 'design', 'binary-tree'],
  300: ['array', 'binary-search', 'dynamic-programming'],
  303: ['array', 'design', 'prefix-sum'],
  304: ['array', 'design', 'prefix-sum', 'matrix'],
  307: ['array', 'design', 'binary-indexed-tree', 'segment-tree'],
  309: ['array', 'dynamic-programming'],
  312: ['array', 'dynamic-programming'],
  315: ['array', 'binary-search', 'divide-and-conquer', 'binary-indexed-tree', 'segment-tree'],
  316: ['string', 'stack', 'greedy', 'monotonic-stack'],
  322: ['array', 'dynamic-programming', 'breadth-first-search'],
  323: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  326: ['math', 'recursion'],
  328: ['linked-list', 'two-pointers'],
  329: ['array', 'depth-first-search', 'breadth-first-search', 'dynamic-programming', 'topological-sort', 'memoization', 'matrix'],
  337: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  338: ['dynamic-programming', 'bit-manipulation'],
  341: ['stack', 'tree', 'depth-first-search', 'design'],
  343: ['math', 'dynamic-programming'],
  344: ['two-pointers', 'string', 'recursion'],
  345: ['two-pointers', 'string'],
  347: ['array', 'hash-table', 'divide-and-conquer', 'sorting', 'heap', 'counting'],
  349: ['array', 'hash-table', 'two-pointers', 'binary-search', 'sorting'],
  350: ['array', 'hash-table', 'two-pointers', 'binary-search', 'sorting'],
  354: ['array', 'binary-search', 'dynamic-programming', 'sorting'],
  371: ['math', 'bit-manipulation'],
  373: ['array', 'binary-search', 'sorting', 'heap', 'matrix'],
  374: ['math', 'binary-search'],
  376: ['array', 'greedy', 'dynamic-programming'],
  377: ['array', 'dynamic-programming', 'backtracking'],
  378: ['array', 'binary-search', 'sorting', 'heap', 'matrix'],
  380: ['hash-table', 'array', 'math', 'design'],
  382: ['linked-list', 'math'],
  383: ['hash-table', 'string', 'counting'],
  384: ['array', 'math', 'design', 'sorting'],
  389: ['hash-table', 'string', 'sorting', 'bit-manipulation'],
  392: ['two-pointers', 'string', 'dynamic-programming'],
  394: ['string', 'stack', 'recursion'],
  395: ['hash-table', 'string', 'sliding-window'],
  397: ['math', 'dynamic-programming', 'bit-manipulation', 'greedy'],
  399: ['array', 'math', 'depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  402: ['string', 'stack', 'greedy', 'monotonic-stack'],
  403: ['array', 'dynamic-programming', 'breadth-first-search'],
  406: ['array', 'greedy', 'sorting'],
  409: ['hash-table', 'string', 'greedy'],
  410: ['array', 'binary-search', 'dynamic-programming', 'greedy', 'prefix-sum'],
  412: ['math', 'string', 'simulation'],
  416: ['array', 'dynamic-programming'],
  417: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  421: ['array', 'hash-table', 'bit-manipulation', 'trie'],
  424: ['hash-table', 'string', 'sliding-window'],
  435: ['array', 'dynamic-programming', 'greedy', 'sorting'],
  437: ['tree', 'depth-first-search', 'binary-tree', 'prefix-sum'],
  438: ['hash-table', 'string', 'sliding-window'],
  442: ['array', 'hash-table', 'sorting'],
  445: ['linked-list', 'math', 'stack'],
  448: ['array', 'hash-table'],
  450: ['tree', 'binary-search-tree', 'binary-tree'],
  451: ['hash-table', 'string', 'sorting', 'counting'],
  452: ['array', 'greedy', 'sorting'],
  454: ['array', 'hash-table'],
  456: ['array', 'stack', 'binary-search', 'monotonic-stack'],
  460: ['hash-table', 'linked-list', 'design'],
  461: ['bit-manipulation'],
  462: ['array', 'math', 'sorting', 'two-pointers'],
  472: ['array', 'string', 'dynamic-programming', 'trie'],
  473: ['array', 'dynamic-programming', 'backtracking', 'bit-manipulation'],
  474: ['array', 'string', 'dynamic-programming'],
  476: ['bit-manipulation'],
  480: ['array', 'hash-table', 'sliding-window', 'heap', 'ordered-set'],
  485: ['array'],
  486: ['array', 'math', 'dynamic-programming', 'game-theory'],
  491: ['array', 'hash-table', 'backtracking'],
  494: ['array', 'dynamic-programming', 'backtracking'],
  496: ['array', 'hash-table', 'stack', 'monotonic-stack'],
  498: ['array', 'matrix', 'simulation'],
  503: ['array', 'stack', 'monotonic-stack'],
  509: ['math', 'dynamic-programming', 'recursion', 'memoization'],
  516: ['string', 'dynamic-programming'],
  518: ['array', 'dynamic-programming'],
  523: ['array', 'hash-table', 'math', 'prefix-sum'],
  525: ['array', 'hash-table', 'prefix-sum'],
  530: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  535: ['hash-table', 'math', 'string', 'design'],
  538: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  540: ['array', 'binary-search'],
  542: ['array', 'dynamic-programming', 'breadth-first-search', 'matrix'],
  543: ['tree', 'depth-first-search', 'binary-tree'],
  547: ['depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  556: ['math', 'two-pointers', 'string'],
  557: ['two-pointers', 'string'],
  560: ['array', 'hash-table', 'prefix-sum'],
  561: ['array', 'greedy', 'sorting'],
  566: ['array', 'matrix', 'simulation'],
  567: ['hash-table', 'two-pointers', 'string', 'sliding-window'],
  572: ['tree', 'depth-first-search', 'string-matching', 'binary-tree', 'rolling-hash'],
  581: ['array', 'two-pointers', 'stack', 'greedy', 'sorting', 'monotonic-stack'],
  583: ['string', 'dynamic-programming'],
  594: ['array', 'hash-table', 'sliding-window', 'counting'],
  598: ['math'],
  600: ['dynamic-programming'],
  605: ['array', 'greedy'],
  611: ['array', 'two-pointers', 'binary-search', 'sorting'],
  621: ['array', 'hash-table', 'greedy', 'sorting', 'heap', 'counting'],
  622: ['linked-list', 'design', 'queue'],
  623: ['tree', 'breadth-first-search', 'binary-tree'],
  629: ['dynamic-programming'],
  632: ['array', 'hash-table', 'greedy', 'sliding-window', 'heap'],
  633: ['math', 'binary-search', 'two-pointers'],
  636: ['string', 'stack'],
  637: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  638: ['array', 'dynamic-programming', 'backtracking', 'memoization'],
  641: ['array', 'linked-list', 'design', 'queue'],
  643: ['array', 'sliding-window'],
  645: ['array', 'math'],
  646: ['array', 'dynamic-programming', 'sorting'],
  647: ['two-pointers', 'string', 'dynamic-programming'],
  648: ['array', 'hash-table', 'string', 'trie', 'sorting'],
  650: ['math', 'dynamic-programming'],
  652: ['hash-table', 'tree', 'depth-first-search', 'binary-tree'],
  653: ['array', 'hash-table', 'two-pointers', 'tree', 'binary-search-tree', 'sorting', 'binary-tree'],
  654: ['array', 'divide-and-conquer', 'stack', 'tree', 'monotonic-stack', 'binary-tree'],
  662: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  664: ['string', 'dynamic-programming'],
  665: ['array', 'greedy'],
  669: ['tree', 'binary-search-tree', 'binary-tree'],
  670: ['greedy', 'math'],
  673: ['array', 'math', 'binary-search', 'dynamic-programming'],
  674: ['array'],
  676: ['hash-table', 'string', 'design', 'trie'],
  677: ['hash-table', 'design', 'trie', 'prefix-sum'],
  684: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  685: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  686: ['string'],
  687: ['tree', 'depth-first-search', 'binary-tree'],
  688: ['dynamic-programming'],
  690: ['hash-table', 'tree', 'depth-first-search', 'breadth-first-search'],
  692: ['array', 'hash-table', 'string', 'sorting', 'heap', 'counting', 'trie'],
  695: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  696: ['two-pointers', 'string', 'dynamic-programming'],
  697: ['array', 'hash-table', 'counting'],
  698: ['array', 'dynamic-programming', 'backtracking', 'bit-manipulation'],
  700: ['tree', 'binary-search-tree', 'binary-tree'],
  701: ['tree', 'binary-search-tree', 'binary-tree'],
  703: ['tree', 'design', 'binary-search-tree', 'binary-tree', 'heap'],
  704: ['array', 'binary-search'],
  712: ['string', 'dynamic-programming'],
  713: ['array', 'binary-search', 'prefix-sum', 'sliding-window', 'two-pointers'],
  714: ['array', 'dynamic-programming', 'greedy'],
  718: ['array', 'binary-search', 'dynamic-programming', 'sliding-window', 'rolling-hash'],
  720: ['array', 'hash-table', 'string', 'trie'],
  721: ['array', 'hash-table', 'union-find', 'string'],
  724: ['array', 'prefix-sum'],
  726: ['hash-table', 'string', 'stack', 'math', 'recursion', 'counting'],
  729: ['array', 'binary-search', 'design', 'ordered-set', 'segment-tree'],
  733: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  735: ['array', 'stack', 'simulation'],
  739: ['array', 'stack', 'monotonic-stack'],
  740: ['array', 'hash-table', 'dynamic-programming'],
  743: ['depth-first-search', 'breadth-first-search', 'graph', 'heap'],
  746: ['array', 'dynamic-programming'],
  752: ['array', 'hash-table', 'breadth-first-search'],
  759: ['array', 'greedy', 'heap', 'sorting', 'ordered-set'],
  763: ['array', 'hash-table', 'two-pointers', 'string', 'greedy'],
  765: ['array', 'hash-table', 'greedy', 'two-pointers', 'union-find', 'sorting'],
  766: ['array', 'matrix'],
  767: ['string', 'hash-table', 'greedy', 'sorting', 'heap', 'counting'],
  769: ['array', 'stack', 'greedy', 'sorting', 'monotonic-stack'],
  771: ['hash-table', 'string', 'counting'],
  773: ['array', 'hash-table', 'breadth-first-search', 'matrix'],
  778: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix', 'heap'],
  783: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  784: ['string', 'backtracking', 'bit-manipulation'],
  785: ['depth-first-search', 'breadth-first-search', 'union-find', 'graph'],
  787: ['dynamic-programming', 'depth-first-search', 'breadth-first-search', 'graph', 'heap'],
  790: ['dynamic-programming', 'matrix'],
  791: ['array', 'hash-table', 'string', 'sorting'],
  792: ['array', 'string', 'trie', 'rolling-hash', 'string-matching'],
  797: ['depth-first-search', 'breadth-first-search', 'graph', 'backtracking'],
  801: ['array', 'dynamic-programming', 'greedy'],
  802: ['depth-first-search', 'breadth-first-search', 'graph', 'topological-sort', 'memoization'],
  820: ['array', 'hash-table', 'string', 'trie'],
  837: ['math', 'dynamic-programming'],
  841: ['hash-table', 'depth-first-search', 'breadth-first-search', 'graph'],
  844: ['two-pointers', 'string', 'stack', 'simulation'],
  845: ['array', 'two-pointers'],
  846: ['array', 'hash-table', 'greedy'],
  849: ['array', 'two-pointers', 'greedy'],
  852: ['array', 'binary-search'],
  860: ['array', 'greedy'],
  861: ['array', 'greedy', 'matrix', 'bit-manipulation'],
  862: ['array', 'hash-table', 'queue', 'sliding-window', 'monotonic-stack', 'prefix-sum'],
  864: ['array', 'hash-table', 'breadth-first-search', 'bit-manipulation', 'matrix'],
  867: ['array', 'matrix', 'simulation'],
  869: ['hash-table', 'math', 'sorting', 'counting'],
  871: ['array', 'dynamic-programming', 'greedy', 'heap'],
  872: ['tree', 'depth-first-search', 'binary-tree'],
  875: ['array', 'binary-search'],
  876: ['linked-list', 'two-pointers'],
  877: ['array', 'math', 'dynamic-programming', 'game-theory'],
  881: ['array', 'greedy', 'sorting', 'two-pointers'],
  884: ['array', 'hash-table', 'string', 'counting'],
  890: ['array', 'hash-table', 'string'],
  892: ['array', 'math', 'geometry'],
  894: ['dynamic-programming', 'binary-tree'],
  896: ['array'],
  897: ['stack', 'tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  901: ['stack', 'design', 'monotonic-stack', 'data-stream'],
  904: ['array', 'hash-table', 'sliding-window'],
  907: ['array', 'stack', 'monotonic-stack'],
  909: ['array', 'hash-table', 'breadth-first-search', 'matrix'],
  912: ['array', 'sorting', 'divide-and-conquer', 'heap'],
  917: ['two-pointers', 'string'],
  918: ['array', 'dynamic-programming', 'queue', 'monotonic-stack'],
  919: ['tree', 'breadth-first-search', 'design', 'binary-tree'],
  921: ['string', 'stack', 'greedy'],
  923: ['array', 'hash-table', 'two-pointers', 'sorting', 'counting'],
  925: ['array', 'string', 'two-pointers'],
  926: ['string', 'dynamic-programming'],
  929: ['array', 'hash-table', 'string'],
  930: ['array', 'hash-table', 'prefix-sum', 'sliding-window'],
  931: ['array', 'dynamic-programming', 'matrix'],
  934: ['array', 'depth-first-search', 'breadth-first-search', 'matrix'],
  937: ['array', 'string', 'sorting'],
  938: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  941: ['array', 'two-pointers'],
  942: ['string', 'greedy'],
  945: ['array', 'greedy', 'sorting'],
  946: ['array', 'stack', 'simulation'],
  947: ['array', 'depth-first-search', 'union-find', 'graph'],
  948: ['array', 'greedy', 'sorting'],
  950: ['array', 'queue', 'simulation', 'sorting'],
  951: ['tree', 'depth-first-search', 'binary-tree'],
  953: ['array', 'hash-table', 'string'],
  954: ['array', 'hash-table', 'greedy', 'sorting'],
  958: ['tree', 'breadth-first-search', 'binary-tree'],
  959: ['array', 'depth-first-search', 'breadth-first-search', 'union-find', 'matrix'],
  962: ['array', 'stack', 'monotonic-stack'],
  968: ['tree', 'depth-first-search', 'dynamic-programming', 'binary-tree'],
  973: ['array', 'math', 'divide-and-conquer', 'sorting', 'heap', 'quickselect', 'geometry'],
  974: ['array', 'hash-table', 'prefix-sum'],
  976: ['array', 'math', 'greedy', 'sorting', 'geometry'],
  977: ['array', 'two-pointers', 'sorting'],
  979: ['tree', 'depth-first-search', 'binary-tree'],
  980: ['array', 'dynamic-programming', 'backtracking', 'matrix'],
  983: ['array', 'dynamic-programming'],
  986: ['array', 'two-pointers'],
  987: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  988: ['tree', 'depth-first-search', 'binary-tree'],
  990: ['array', 'hash-table', 'union-find', 'string'],
  992: ['array', 'hash-table', 'sliding-window', 'counting'],
  994: ['array', 'breadth-first-search', 'matrix'],
  997: ['array', 'hash-table', 'graph'],
  1007: ['array', 'greedy'],
  1009: ['math', 'bit-manipulation'],
  1011: ['array', 'binary-search'],
  1014: ['array', 'dynamic-programming'],
  1018: ['array', 'math'],
  1022: ['tree', 'depth-first-search', 'binary-tree'],
  1028: ['tree', 'depth-first-search', 'string', 'binary-tree'],
  1038: ['tree', 'depth-first-search', 'binary-search-tree', 'binary-tree'],
  1039: ['array', 'math', 'dynamic-programming'],
  1052: ['array', 'sliding-window'],
  1061: ['array', 'hash-table', 'string', 'union-find'],
  1072: ['array', 'hash-table', 'matrix'],
  1079: ['hash-table', 'string', 'dynamic-programming', 'backtracking', 'counting'],
  1080: ['tree', 'depth-first-search', 'binary-tree'],
  1081: ['string', 'stack', 'greedy', 'monotonic-stack'],
  1092: ['string', 'dynamic-programming'],
  1105: ['array', 'dynamic-programming'],
  1106: ['string', 'stack', 'recursion'],
  1110: ['tree', 'depth-first-search', 'binary-tree'],
  1123: ['tree', 'depth-first-search', 'hash-table', 'breadth-first-search', 'binary-tree'],
  1128: ['array', 'hash-table', 'counting'],
  1140: ['array', 'math', 'dynamic-programming', 'game-theory'],
  1161: ['tree', 'depth-first-search', 'breadth-first-search', 'binary-tree'],
  1190: ['string', 'stack'],
  1200: ['array', 'sorting'],
  1233: ['array', 'string', 'depth-first-search', 'trie'],
  1248: ['array', 'hash-table', 'math', 'sliding-window', 'prefix-sum'],
  1261: ['hash-table', 'tree', 'depth-first-search', 'breadth-first-search', 'design', 'binary-tree'],
  1262: ['array', 'dynamic-programming'],
  1266: ['array', 'math'],
  1267: ['array', 'counting', 'matrix'],
}

/** Return tags for a given problem number. Returns [] if not in the map. */
export function getTagsForProblem(number: number): Tag[] {
  return PROBLEM_TAGS[number] ?? []
}

/**
 * Return all tags sorted by frequency descending.
 * Each entry: { tag, label, count }
 */
export function getAllTags(): { tag: Tag; label: string; count: number }[] {
  const counts: Record<string, number> = {}
  for (const tags of Object.values(PROBLEM_TAGS)) {
    for (const tag of tags) {
      counts[tag] = (counts[tag] ?? 0) + 1
    }
  }
  return Object.entries(counts)
    .map(([tag, count]) => ({
      tag,
      label: TAG_LABELS[tag] ?? tag.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      count,
    }))
    .sort((a, b) => b.count - a.count)
}

/** Return all problem numbers that have a given tag */
export function getProblemNumbersByTag(tag: Tag): number[] {
  return Object.entries(PROBLEM_TAGS)
    .filter(([, tags]) => tags.includes(tag))
    .map(([n]) => parseInt(n))
    .sort((a, b) => a - b)
}
